#!/usr/bin/env perl
use FindBin qw($Bin);
use lib "$Bin/../lib";
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::Plumbing;
use GoGameTools::Porcelain::EasyGoWrite;
my %opt = get_options(
    extra_opts => [qw(zip|z=s)],
    required   => [qw(zip)]
);
my $porcelain = GoGameTools::Porcelain::EasyGoWrite->new(zip => $opt{zip});
run_pipe(pipe_decode_json_from_stdin(), $porcelain->run);
