#!/usr/bin/env perl
use FindBin qw($Bin);
use lib "$Bin/../lib";
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::Plumbing;
use GoGameTools::Porcelain::MakeLinearStory;
my %opt = get_options(
    expect_stdin => 0,
    extra_opts   => [
        qw(
          story|s=s
          output|o=s
          )
    ],
    required => [qw(story output)],
);
my $porcelain = GoGameTools::Porcelain::MakeLinearStory->new(
    story_file  => $opt{story},
    output_file => $opt{output}
);
# run_pipe($porcelain->run, pipe_trees_to_sgj(), pipe_encode_json_to_stdout());
run_pipe($porcelain->run, pipe_write());

=pod

Takes a story that specifies paths from certain trees and creates a linear list
of nodes. Useful for explaining a concept, or lectures in general.

        gogame-make-linear-story -s story.json -o result.sgf

=cut
