#!/usr/bin/env perl
use FindBin qw($Bin);
use lib "$Bin/../lib";
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::JSON;
my %opt = get_options(
    expect_stdin => 1,
    extra_opts => [qw(delete-private-refs|p delete-secret-problems|s basedir|d=s)],
);
my $json      = do { local $/; <STDIN> };
my $porcelain = GoGameTools::Porcelain::SiteMungeSGJ->new(
    delete_private_refs    => $opt{'delete-private-refs'},
    delete_secret_problems => $opt{'delete-secret-problems'},
    basedir                => $opt{basedir},
)->run;
say json_encode($porcelain->(json_decode($json)));

=pod

=item C<--delete-private-refs>

Takes the SGJ of generated problems and removes private refs - that is, those
starting with C<p/>, then prints the resulting SGJ. When this is piped to the
site generator, it will not include menu items that depend on those private
refs.

=cut
