#!/usr/bin/env perl
use FindBin qw($Bin);
use lib "$Bin/../lib";
use GoGameTools::features;
use GoGameTools::Plumbing;
use GoGameTools::Porcelain::SiteWrite;
use GoGameTools::Util;
my %opt = get_options(
    expect_stdin => 1,
    extra_opts   => [qw(site_dir=s www-dir=s viewer=s delete-metadata)],
    required     => [qw(www-dir viewer)]
);
my $viewer_class = load_viewer_class($opt{viewer});
my $porcelain    = GoGameTools::Porcelain::SiteWrite->new(
    site_dir        => $opt{site_dir},
    viewer_delegate => $viewer_class->new,
    www_dir         => $opt{'www-dir'},
    delete_metadata => $opt{'delete-metadata'},
);
run_pipe(pipe_decode_json_from_stdin(), $porcelain->run);

=pod

Expects site data on STDIN.
Writes site iles.
