#!/usr/bin/env perl
use FindBin qw($Bin);
use lib "$Bin/../lib";
use GoGameTools::features;
use GoGameTools::Plumbing;
use GoGameTools::Porcelain::SiteGenData;
use GoGameTools::Util;
my %opt = get_options(
    expect_stdin => 1,
    extra_opts   => [qw(nopermalinks menu|m=s@)]
);
my $porcelain = GoGameTools::Porcelain::SiteGenData->new(
    no_permalinks => $opt{nopermalinks},
    menu          => $opt{menu},
);
run_pipe(pipe_decode_json_from_stdin(),
    $porcelain->run, pipe_encode_json_to_stdout);

=pod

Expects a list of SGJ problem objects on STDIN.
Prints site data.
