package GoGameTools::Porcelain::SiteGenData;
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::JSON;
use GoGameTools::Parser::FilterQuery;
use Path::Tiny;
use Digest::SHA qw(sha1_hex);
use utf8;
use GoGameTools::Class qw($delete_metadata $no_permalinks @menu);
my $FILTER = '$filter';

sub run ($self) {
    return (
        sub ($collection) {

            # munge the SGJ objects so they look like eval_query() expects
            my (%problems_with_collection_id, %topic_index);
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{problem_id} = utf8_sha1_hex($sgj_obj->{sgf})
                  unless $self->no_permalinks;
                $sgj_obj->{collection_id} =
                  utf8_sha1_hex(sprintf '%s %s', $sgj_obj->{metadata}->@{qw(filename index)});
                $sgj_obj->{topics} = [];
                $sgj_obj->{vars}   = query_vars_from_sgj($sgj_obj);
                push @{ $problems_with_collection_id{ $sgj_obj->{collection_id} } //= [] },
                  $sgj_obj;
            }

            # concatenate the lists from all menu locations
            my @sections = (
                get_basic_menu(), map { json_decode(path($_)->slurp_utf8)->@* } $self->menu->@*
            );

            # For each topic, find the problems matching the topic's filter
            # expression. Store them with the topic.
            #
            # @result_sections and @result_topics_for_section are intermediate variables so
            # we can only take those sections and topics that actually contain problems.
            my @result_sections;
            for my $section (@sections) {
                my @result_topics_for_section;
                handle_computed_properties_for_section($section);
                for my $topic ($section->{topics}->@*) {
                    my $expr = parse_filter_query($topic->{filter})
                      // die "can't parse filter query $topic->{filter}\n";
                    $topic->{problems} =
                      [ grep { eval_query(expr => $expr, vars => $_->{vars}) } $collection->@* ];
                    next unless $topic->{problems}->@*;

                    # The filename that the topic's problem collection will be written to.
                    $topic->{filename} = $topic->{filter} =~ s/\W+/-/gr =~ s/^-|-$//gr;

                    # When a problem is displayed, we want to show links to topics where
                    # this problem occurs. So build up a topic index that contains the
                    # button title and the topic's collection filename.
                    my %topic_for_index = $topic->%*;
                    $topic_for_index{count} = scalar($topic_for_index{problems}->@*);
                    delete $topic_for_index{problems};
                    $topic_index{ $topic->{filename} } = \%topic_for_index;

                    # For each problem in the current topic's collection, remember that
                    # these problems occurred in this topic. So at the end of the loop each
                    # problem contains a list of all the topics it occurs in.
                    push $_->{topics}->@*, $topic->{filename} for $topic->{problems}->@*;
                    push @result_topics_for_section, $topic;
                }
                if (@result_topics_for_section) {
                    $section->{topics} = \@result_topics_for_section;
                    push @result_sections, $section;
                }
            }
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{related_positions} =
                  scalar($problems_with_collection_id{ $sgj_obj->{collection_id} }->@*);

                # include refs and tags so that subset filtering can work
                $sgj_obj->{$_} = $sgj_obj->{metadata}{$_} for qw(refs tags);

                # delete things that the site doesn't need
                delete $sgj_obj->{$_} for qw(game_info vars);
                delete $sgj_obj->{metadata}{input_filename};
                delete $sgj_obj->{metadata} if $self->delete_metadata;
            }

            # delete entries from the topic index that don't have problems
            my @empty_topic_index_keys;
            while (my ($k, $v) = each %topic_index) {
                push @empty_topic_index_keys, $k if $v->{count} == 0;
            }
            delete @topic_index{@empty_topic_index_keys};
            return +{
                menu             => \@result_sections,
                by_collection_id => \%problems_with_collection_id,
                topic_index      => \%topic_index,
                full_collection  => $collection,
            };
        }
    );
}

# sha1_hex() can't deal with Unicode, so this version converts it to bytes
sub utf8_sha1_hex ($data) {
    utf8::encode($data);
    return sha1_hex($data);
}

sub get_basic_menu {
    my @menu = (
        {   text   => 'Techniques',
            topics => [
                {   filter    => '#double_atari',
                    text      => 'Double atari',
                    thumbnail => $FILTER,
                },
                {   filter    => '#counteratari',
                    text      => 'Counter-atari',
                    thumbnail => $FILTER,
                },
                {   filter    => '#lining_up',
                    text      => 'Lining up',
                    thumbnail => $FILTER,
                },
                {   filter    => '#dent',
                    text      => 'Dent',
                    thumbnail => $FILTER,
                },
                {   filter    => '#wedge',
                    text      => 'Wedge',
                    thumbnail => $FILTER,
                },
                {   filter    => '#bend_wedge',
                    text      => 'Bend-wedge',
                    thumbnail => $FILTER,
                },
                {   filter    => '#clamp',
                    text      => 'Clamp',
                    thumbnail => $FILTER,
                },
                {   filter    => '#counterclamp',
                    text      => 'Counter-clamp',
                    thumbnail => $FILTER,
                },
                {   filter    => '#hane_and_cut',
                    text      => 'Hane and cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#hane_and_nakade',
                    text      => 'Hane and nakade',
                    thumbnail => $FILTER,
                },
                {   filter    => '#peep_and_cut',
                    text      => 'Peep and cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#push_and_cut',
                    text      => 'Push and cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#push_and_backtrack',
                    text      => 'Push and backtrack',
                    thumbnail => $FILTER,
                },
                {   filter    => '#jumping_over_wall',
                    text      => 'Jumping over the wall',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_draw_back',
                    text      => 'Attach and draw back',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_extend',
                    text      => 'Attach and extend',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_hane',
                    text      => 'Attach and hane',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_crosscut',
                    text      => 'Attach and crosscut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_block',
                    text      => 'Attach and block',
                    thumbnail => $FILTER,
                },
                {   filter    => '#attach_and_bulge',
                    text      => 'Attach and bulge',
                    thumbnail => $FILTER,
                },
                {   filter    => '#push_and_placement',
                    text      => 'Push and placement',
                    thumbnail => $FILTER,
                },
                {   filter    => '#clamp_against_attachment',
                    text      => 'Clamp against an attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#elephant_eye',
                    text      => "Elephant's eye",
                    thumbnail => $FILTER,
                },
                {   filter    => '#diagonal_cover',
                    text      => 'Diagonal cover',
                    thumbnail => $FILTER,
                },
                {   filter    => '#knights_cover',
                    text      => "Knight's cover",
                    thumbnail => $FILTER,
                },
                {   filter    => '#large_knights_cover',
                    text      => "Large knight's cover",
                    thumbnail => $FILTER,
                },
                {   filter    => '#shoulder_hit',
                    text      => 'Shoulder hit',
                    thumbnail => $FILTER,
                },
                {   filter    => '#shoulder_cut',
                    text      => 'Shoulder cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#jump_attachment',
                    text      => 'Jump-attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#nose_attachment',
                    text      => 'Nose attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#table_attachment',
                    text      => 'Table attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#anti_tower_peep_placement',
                    text      => 'Anti tower peep placement',
                    thumbnail => $FILTER,
                },
                {   filter    => '#belly_attachment',
                    text      => 'Belly attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#armpit',
                    text      => 'Armpit',
                    thumbnail => $FILTER,
                },
                {   filter    => '#ankle_hook',
                    text      => 'Ankle hook',
                    thumbnail => $FILTER,
                },
                {   filter    => '#breaking_the_wing',
                    text      => 'Breaking the wing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cap',
                    text      => 'Cap',
                    thumbnail => $FILTER,
                },
                {   filter    => '#caterpillar_connection',
                    text      => 'Caterpillar connection',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cave',
                    text      => 'Cave',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cranes_nest',
                    text      => "Crane's nest",
                    thumbnail => $FILTER,
                },
                {   filter    => '#driving',
                    text      => 'Driving',
                    thumbnail => $FILTER,
                },
                {   filter    => '#dogleg',
                    text      => 'Dog leg',
                    thumbnail => $FILTER,
                },
                {   filter    => '#crawling_under_the_door',
                    text      => 'Crawling under the door',
                    thumbnail => $FILTER,
                },
                {   filter    => '#snapback',
                    text      => 'Snapback, all',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_snapback',
                    text      => 'Double snapback',
                    collate   => 'Snapback, double',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_hane_edge_squeeze',
                    text      => 'Double hane edge squeeze',
                    thumbnail => $FILTER,
                },
                {   filter    => '#eiffel_tower',
                    text      => 'Eiffel tower',
                    thumbnail => $FILTER,
                },
                {   filter    => '#eternal_life',
                    text      => 'Eternal life',
                    thumbnail => $FILTER,
                },
                {   filter    => '#eye_in_the_stomach',
                    text      => 'Eye in the stomach',
                    thumbnail => $FILTER,
                },
                {   filter    => '#flower_six',
                    text      => 'Flower six',
                    thumbnail => $FILTER,
                },
                {   filter    => '#grappling_hook',
                    text      => 'Grappling hook',
                    thumbnail => $FILTER,
                },
                {   filter    => '#hane_at_the_head',
                    text      => 'Hane at the head',
                    thumbnail => $FILTER,
                },
                {   filter    => '#ladder',
                    text      => 'Ladder',
                    collate   => 'Ladder, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#spiral_ladder',
                    text      => 'Spiral ladder',
                    collate   => 'Ladder, spiral',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_ladder',
                    text      => 'Double ladder',
                    collate   => 'Ladder, double',
                    thumbnail => $FILTER,
                },
                {   filter    => '#loose_ladder',
                    text      => 'Loose ladder',
                    collate   => 'Ladder, loose',
                    thumbnail => $FILTER,
                },
                {   filter    => '#squeezing',
                    text      => 'Squeezing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#mouse_stealing_oil',
                    text      => 'Mouse stealing oil',
                    thumbnail => $FILTER,
                },
                {   filter    => '#monkey_jump',
                    text      => 'Monkey jump',
                    thumbnail => $FILTER,
                },
                {   filter    => '#net',
                    text      => 'Net',
                    collate   => 'Net, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#knights_net',
                    text      => "Knight's net",
                    collate   => 'Net, knights',
                    thumbnail => $FILTER,
                },
                {   filter    => '#first_line_descent',
                    text      => 'First-line descent',
                    thumbnail => $FILTER,
                },
                {   filter    => '#parallel_bars',
                    text      => 'Parallel bars',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rooster_on_one_leg',
                    text      => 'Rooster on one leg',
                    thumbnail => $FILTER,
                },
                {   filter    => '#sacrifice_two',
                    text      => 'Sacrifice two stones',
                    thumbnail => $FILTER,
                },
                {   filter    => '#shimetsuke',
                    text      => 'Tightening',
                    thumbnail => $FILTER,
                },
                {   filter    => '#stick_connection',
                    text      => 'Stick connection',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_knights_connection',
                    text      => "Double knight's connection",
                    thumbnail => $FILTER,
                },
                {   filter    => '#symmetry',
                    text      => 'Symmetry',
                    thumbnail => $FILTER,
                },
                {   filter    => '#tanuki_belly',
                    text      => 'Tanuki drumming his belly',
                    thumbnail => $FILTER,
                },
                {   filter    => '#three_is_one',
                    text      => 'Three is one',
                    thumbnail => $FILTER,
                },
                {   filter    => '#tombstone',
                    text      => 'Tombstone',
                    thumbnail => $FILTER,
                },
                {   filter    => '#pushing_twice_then_keima',
                    text      => 'Pushing twice, then keima',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cut_under_the_stones',
                    text      => 'Under the stones, then cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#placement_under_the_stones',
                    text      => 'Under the stones, then placement',
                    thumbnail => $FILTER,
                },
                {   filter    => '#windmill',
                    text      => 'Windmill',
                    thumbnail => $FILTER,
                },
                {   filter    => '#ko_lock',
                    text      => 'Ko lock',
                    thumbnail => $FILTER,
                },
                {   filter    => '#connect_and_die',
                    text      => 'Connect and die',
                    thumbnail => $FILTER,
                },
                {   filter    => '#elbow_lock',
                    text      => 'Elbow lock',
                    thumbnail => $FILTER,
                },
                {   filter    => '#carpenters_connection',
                    text      => "Carpenter's square connection",
                    thumbnail => $FILTER,
                },
                {   filter    => '#guzumi',
                    text      => 'Good empty triangle',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cork_in_the_bottle',
                    text      => 'Cork in the bottle',
                    thumbnail => $FILTER,
                },
                {   filter    => '#angle_play',
                    text      => 'Angle play',
                    thumbnail => $FILTER,
                },
                {   filter    => '#crosscut',
                    text      => 'Crosscut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#peep',
                    text      => 'Peep',
                    collate   => 'Peep, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#resisting_peep',
                    text      => 'Resisting a peep',
                    collate   => 'Peep, resisting',
                    thumbnail => $FILTER,
                },
                {   filter    => '#preventing_bamboo',
                    text      => 'Preventing the bamboo',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cut_to_defend_cut',
                    text      => 'Cut to defend against a cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#daidaigeima',
                    text      => "Extra-large knight's move",
                    thumbnail => $FILTER,
                },
                {   filter    => '#pushing_from_behind',
                    text      => 'Pushing from behind',
                    thumbnail => $FILTER,
                },
                {   filter    => '#second_line_diagonal',
                    text      => 'Diagonal move on the second line',
                    thumbnail => $FILTER,
                },
                {   filter    => '#two_recapture_one',
                    text      => 'Capturing two stones, recapturing one',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capturing_two_for_two_eyes',
                    text      => 'Capturing two stones, getting two eyes',
                    thumbnail => $FILTER,
                },
                {   filter    => '#wedge_separate',
                    text      => 'Wedge to separate',
                    thumbnail => $FILTER,
                },
                {   filter    => '#invading_3_extension',
                    text      => 'Invading a three-space extension',
                    thumbnail => $FILTER,
                },
                {   filter    => '#trumpet_connection',
                    text      => 'Trumpet connection',
                    thumbnail => $FILTER,
                },
                {   filter    => '#unstable_connection',
                    text      => 'Unstable connections',
                    thumbnail => $FILTER,
                },
                {   filter    => '#cat_face',
                    text      => "Cat's face",
                    collate   => 'Face, cat',
                    thumbnail => $FILTER,
                },
                {   filter    => '#dog_face',
                    text      => "Dog's face",
                    collate   => 'Face, dog',
                    thumbnail => $FILTER,
                },
                {   filter    => '#breaking_dog_face',
                    text      => "Breaking the dog's face",
                    collate   => 'Face, dog, break',
                    thumbnail => $FILTER,
                },
                {   filter    => '#horse_face',
                    text      => "Horse's face",
                    collate   => 'Face, horse',
                    thumbnail => $FILTER,
                },
                {   filter    => '#giraffe_face',
                    text      => "Giraffe's face",
                    collate   => 'Face, giraffe',
                    thumbnail => $FILTER,
                },
                {   filter    => '#bumping',
                    text      => 'Bumping',
                    thumbnail => $FILTER,
                },
                {   filter    => '#flying_double_clamp',
                    text      => 'Flying double clamp',
                    thumbnail => $FILTER,
                },
                {   filter    => '#throwing_in',
                    text      => 'Throwing in',
                    thumbnail => $FILTER,
                },
                {   filter    => '#crossing_the_lair',
                    text      => 'Crossing the Lair',
                    thumbnail => $FILTER,
                },
                {   filter    => '#pinch',
                    text      => 'Pinch',
                    thumbnail => $FILTER,
                },
                {   filter    => '#braid',
                    text      => 'Braid',
                    thumbnail => $FILTER,
                },
                {   filter    => '#first_line_empty_triangle',
                    text      => 'Empty triangle on the first line',
                    thumbnail => $FILTER,
                },
                {   filter    => '#across_attach',
                    text      => 'Across attach',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rhombus_attach',
                    text      => 'Rhombus attach',
                    thumbnail => $FILTER,
                },
                {   filter    => '#diagonal_attachment',
                    text      => 'Diagonal attachment',
                    thumbnail => $FILTER,
                },
                {   filter    => '#tigers_mouth',
                    text      => "Tiger's mouth",
                    thumbnail => $FILTER,
                },
                {   filter    => '#nobikiri',
                    text      => 'Stretching in',
                    thumbnail => $FILTER,
                },
                {   filter    => '#bad_sente',
                    text      => 'Bad sente',
                    thumbnail => $FILTER,
                }
            ]
        },
        {   text   => 'Opening',
            topics => [
                {   filter    => '#making_a_position',
                    text      => 'Making a position',
                    thumbnail => $FILTER,
                },
                {   filter    => '#extending',
                    text      => 'Extending',
                    thumbnail => $FILTER,
                },
                {   filter    => '#drawing_near',
                    text      => 'Drawing near',
                    thumbnail => $FILTER,
                },
                {   filter    => '#checking_extension',
                    text      => 'Checking extension',
                    thumbnail => $FILTER,
                },
                {   filter    => '#enlarging',
                    text      => 'Enlarging',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_a_triangular_framework',
                    text      => 'Making a triangular framework',
                    collate   => 'Framework, 3, making',
                    thumbnail => $FILTER,
                },
                {   filter    => '#preventing_a_triangular_framework',
                    text      => 'Preventing a triangular framework',
                    collate   => 'Framework, 3, preventing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_a_rectangular_framework',
                    text      => 'Making a rectangular framework',
                    collate   => 'Framework, 4, making',
                    thumbnail => $FILTER,
                },
                {   filter    => '#enlarging_while_limiting',
                    text      => 'Enlarging while limiting',
                    thumbnail => $FILTER,
                },
                {   filter    => '#reducing_from_above',
                    text      => 'Reducing from above',
                    thumbnail => $FILTER,
                },
                {   filter    => '#surrounding',
                    text      => 'Surrounding',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/low-chinese',
                    text      => 'Low chinese fuseki',
                    collate   => 'Fuseki, chinese, low',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/high-chinese',
                    text      => 'High chinese fuseki',
                    collate   => 'Fuseki, chinese, high',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/mini-chinese',
                    text      => 'Mini chinese fuseki',
                    collate   => 'Fuseki, chinese, mini',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/micro-chinese',
                    text      => 'Micro chinese fuseki',
                    collate   => 'Fuseki, chinese, micro',
                    thumbnail => $FILTER,
                },
                {   filter    => '#kobayashi_fuseki',
                    text      => '@fuseki/kobayashi',
                    collate   => 'Fuseki, Kobayashi',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/facing-34',
                    text      => 'Facing 3-4 points',
                    collate   => 'Fuseki, 3-4, facing',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/opposing-34',
                    text      => 'Opposing 3-4 points',
                    collate   => 'Fuseki, 3-4, opposing',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/nirensei',
                    text      => 'Nirensei',
                    collate   => 'Fuseki, star points, 2',
                    thumbnail => $FILTER,
                },
                {   filter    => '@fuseki/sanrensei',
                    text      => 'Sanrensei',
                    collate   => 'Fuseki, star points, 3',
                    thumbnail => $FILTER,
                }
            ]
        },
        {   topics => [
                {   filter    => '#separating',
                    text      => 'Separating',
                    thumbnail => $FILTER,
                },
                {   filter    => '#pressing_down',
                    text      => 'Pressing down',
                    thumbnail => $FILTER,
                },
                {   filter    => '#sealing_in',
                    text      => 'Sealing in',
                    thumbnail => $FILTER,
                },
                {   filter    => '#spoiling_shape',
                    text      => 'Spoiling shape, all',
                    collate   => 'Spoiling shape, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#forcing_into_empty_triangle and not #forcing_into_farmers_hat',
                    text      => 'Empty triangle',
                    collate   => 'Spoiling shape, empty triangle',
                    thumbnail => 'empty-triangle.png',
                },
                {   filter    => '#forcing_into_farmers_hat',
                    text      => "Farmer's hat",
                    collate   => "Spoiling shape, farmer's hat",
                    thumbnail => $FILTER,
                },
                {   filter    => '#forcing_into_dumpling',
                    text      => 'Dumpling',
                    collate   => 'Spoiling shape, dumpling',
                    thumbnail => $FILTER,
                },
                {   filter    => '#probing',
                    text      => 'Probing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_heavy',
                    text      => 'Making heavy',
                    thumbnail => $FILTER,
                },
                {   filter    => '#overconcentrating',
                    text      => 'Overconcentrating',
                    thumbnail => $FILTER,
                },
                {   filter    => '#creating_weaknesses',
                    text      => 'Creating weaknesses',
                    collate   => 'Creating weaknesses, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#creating_cuts',
                    text      => 'Creating cuts',
                    collate   => 'Creating weaknesses, cuts',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_double_threats',
                    text      => 'Making double threats',
                    thumbnail => $FILTER,
                },
                {   filter    => '#taking_away_base',
                    text      => 'Taking away the base',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capturing',
                    text      => 'Capturing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_territory',
                    text      => 'Making territory',
                    thumbnail => $FILTER,
                },
                {   filter    => '#intimidating_with_ko',
                    text      => 'Intimidating with ko',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_fist',
                    text      => 'Making a fist',
                    thumbnail => $FILTER,
                },
                {   filter    => '#invading',
                    text      => 'Invading',
                    thumbnail => $FILTER,
                },
                {   filter    => '#kikashi',
                    text      => 'Kikashi',
                    thumbnail => $FILTER,
                },
                {   filter    => '#bullying',
                    text      => 'Bullying',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capping',
                    text      => 'Capping',
                    thumbnail => $FILTER,
                },
                {   filter    => '#leaning_attack',
                    text      => 'Leaning attack',
                    thumbnail => $FILTER,
                },
                {   filter    => '#splitting_attack',
                    text      => 'Splitting attack',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Attacking',
        },
        {   topics => [
                {   filter    => '#connecting',
                    text      => 'Connecting',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capturing_key_stones',
                    text      => 'Capturing key stones',
                    thumbnail => $FILTER,
                },
                {   filter    => '#developing',
                    text      => 'Developing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#escaping',
                    text      => 'Escaping',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_shape',
                    text      => 'Making shape',
                    thumbnail => $FILTER,
                },
                {   filter    => '#taking_sente',
                    text      => 'Taking sente',
                    thumbnail => $FILTER,
                },
                {   filter    => '#sabaki',
                    text      => 'Handling weak stones',
                    thumbnail => $FILTER,
                },
                {   filter    => '#striking_back',
                    text      => 'Striking back',
                    thumbnail => $FILTER,
                },
                {   filter    => '#defending_against_multiple_threats',
                    text      => 'Defending against multiple threats',
                    thumbnail => $FILTER,
                },
                {   filter    => '#solidifying_base',
                    text      => 'Solidifying the base',
                    thumbnail => $FILTER,
                },
                {   filter    => '#defending_base',
                    text      => 'Defending the base',
                    thumbnail => $FILTER,
                },
                {   filter    => '#linking_up',
                    text      => 'Linking up',
                    thumbnail => $FILTER,
                },
                {   filter    => '#resisting_with_ko',
                    text      => 'Resisting with ko',
                    thumbnail => $FILTER,
                },
                {   filter    => '#forcing_before_defending',
                    text      => 'Forcing before defending',
                    thumbnail => $FILTER,
                },
                {   filter    => '#indirect_defense',
                    text      => 'Indirect defense',
                    thumbnail => $FILTER,
                },
                {   filter    => '#refuting_overplay',
                    text      => 'Refuting an overplay',
                    thumbnail => $FILTER,
                },
                {   filter    => '#trick_play',
                    text      => 'Trick play',
                    thumbnail => $FILTER,
                },
                {   filter    => '#deny_kikashi',
                    text      => 'Denying kikashi',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Defending',
        },
        {   topics => [
                {   filter    => '#sacrificing_junk_stones',
                    text      => 'Sacrificing junk stones',
                    thumbnail => $FILTER,
                },
                {   filter    => '#chasing_junk_stones',
                    text      => 'Chasing junk stones',
                    thumbnail => $FILTER,
                },
                {   filter    => '#walking_ahead',
                    text      => 'Walking ahead',
                    thumbnail => $FILTER,
                },
                {   filter    => '#pushing_from_weak_area',
                    text      => 'Pushing from weakness',
                    thumbnail => $FILTER,
                },
                {   filter    => '#joseki_choice',
                    text      => 'Choice of joseki',
                    thumbnail => $FILTER,
                },
                {   filter    => '#direction_of_attack',
                    text      => 'Direction of attack',
                    thumbnail => $FILTER,
                },
                {   filter    => '#value_of_sides',
                    text      => 'Value of sides',
                    thumbnail => $FILTER,
                },
                {   filter    => '#playing_away_from_thickness',
                    text      => 'Playing away from thickness',
                    thumbnail => $FILTER,
                },
                {   filter    => '#avoiding_being_enclosed',
                    text      => 'Avoiding being enclosed',
                    thumbnail => $FILTER,
                },
                {   filter    => '#leaving_aji',
                    text      => 'Leaving aji',
                    thumbnail => $FILTER,
                },
                {   filter    => '#good_ugly_keima_cut',
                    text      => 'Good ugly keima cut',
                    thumbnail => $FILTER,
                },
                {   filter    => '#tenuki',
                    text      => 'Tenuki',
                    thumbnail => $FILTER,
                },
                {   filter    => '#running_battle',
                    text      => 'Running battle',
                    thumbnail => $FILTER,
                },
                {   filter    => '#tennouzan',
                    text      => 'Commanding the high point',
                    thumbnail => $FILTER,
                },
                {   filter    => '#crossfight',
                    text      => 'Four cut groups',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Strategy',
        },
        {   topics => [
                {   filter    => '#solidifying_base and #taking_away_base',
                    text      => 'Base of both sides',
                    thumbnail => 'base-of-both-sides.png',
                },
                {   filter    => '#handling_invasion',
                    text      => 'Handling an invasion',
                    thumbnail => $FILTER,
                },
                {   filter    => '#speculative_invasion',
                    text      => 'Speculative invasion',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Multiple objectives',
        },
        {   topics => [
                {   filter    => '#breaking_in',
                    text      => 'Breaking in',
                    thumbnail => $FILTER,
                },
                {   filter    => '#encroaching',
                    text      => 'Encroaching on territory',
                    collate   => 'Encroaching, doing',
                    thumbnail => $FILTER,
                },
                {   filter    => '#stopping_encroachments',
                    text      => 'Stopping encroachments',
                    collate   => 'Encroaching, stopping',
                    thumbnail => $FILTER,
                },
                {   filter    => '#large_yose',
                    text      => 'Large yose',
                    thumbnail => $FILTER,
                },
                {   filter    => '#threatening_to_kill',
                    text      => 'Threatening to kill',
                    thumbnail => $FILTER,
                },
                {   filter    => '#forcing_removal',
                    text      => 'Forcing removal',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_endgame_attacks',
                    text      => 'Double endgame attacks',
                    thumbnail => $FILTER,
                },
                {   filter    => '#double_endgame_defenses',
                    text      => 'Double endgame defenses',
                    thumbnail => $FILTER,
                },
                {   filter    => '#closing_in_sente',
                    text      => 'Closing boundaries in sente',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Endgame',
        },
        {   text   => 'Living',
            topics => [
                {   filter    => '#living',
                    text      => 'All',
                    rel_text  => 'Living, all',
                    collate   => 'Living, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#securing_eye_shape',
                    text      => 'Securing eye shape',
                    rel_text  => 'Living by securing eye shape',
                    collate   => 'Living, securing eye shape',
                    thumbnail => $FILTER,
                },
                {   filter    => '#enlarging_eye_space',
                    text      => 'Enlarging eye space',
                    rel_text  => 'Living by enlarging eye space',
                    collate   => 'Living, enlarging eye space',
                    thumbnail => $FILTER,
                },
                {   filter    => '#living_with_false_eyes',
                    text      => 'Living with false eyes',
                    collate   => 'Living, false eyes',
                    thumbnail => $FILTER,
                },
                {   filter    => '#living_with_seki',
                    text      => 'Living with seki',
                    collate   => 'Living, seki',
                    thumbnail => $FILTER,
                },
                {   filter    => '#squashing',
                    text      => 'Squashing',
                    rel_text  => 'Living by squashing',
                    collate   => 'Living, squashing',
                    thumbnail => $FILTER,
                },
                {   text      => 'Living with Ko',
                    filter    => '#living_with_ko',
                    collate   => 'Living, ko, 1',
                    thumbnail => $FILTER,
                },
                {   text      => 'Living with double ko',
                    filter    => '#living_with_double_ko',
                    collate   => 'Living, ko, 2',
                    thumbnail => $FILTER,
                },

                # Making one eye
                {   filter    => '@tsumego/making-one-eye/other',
                    text      => 'Making one eye, other',
                    collate   => 'Making one eye, 2',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/making-one-eye/second-line-shape',
                    text      => 'Making one eye, second-line shapes',
                    collate   => 'Making one eye, 1',
                    thumbnail => $FILTER,
                },
            ]
        },
        {   text   => 'Killing',
            topics => [
                {   filter    => '#killing',
                    text      => 'All',
                    rel_text  => 'Killing, all',
                    collate   => 'Killing, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '#nakade',
                    text      => 'Nakade',
                    rel_text  => 'Killing with nakade',
                    collate   => 'Killing, nakade',
                    thumbnail => $FILTER,
                },
                {   filter    => '#bent_four_in_the_corner',
                    text      => 'Bent four in the corner',
                    collate   => 'Killing, bent four in the corner',
                    thumbnail => $FILTER,
                },
                {   filter    => '#making_a_false_eye',
                    text      => 'Making a false eye',
                    rel_text  => 'Killing by making a false eye',
                    collate   => 'Killing, false eye',
                    thumbnail => $FILTER,
                },
                {   filter    => '#killing_with_ko',
                    text      => 'Killing with ko',
                    collate   => 'Killing, ko, 1',
                    thumbnail => $FILTER,
                },
                {   filter    => '#killing_with_double_ko',
                    text      => 'Killing with double ko',
                    collate   => 'Killing, ko, 2',
                    thumbnail => $FILTER,
                },
                {   filter    => '#ten_thousand_year_ko',
                    text      => '10,000 year ko',
                    collate   => 'Killing, ko, 3',
                    thumbnail => $FILTER,
                },
            ]
        },
        {   text   => 'Real-game life-and-death',
            topics => [

                # Real-game corners
                {   filter    => '@tsumego/real/corner',
                    text      => 'Real-game corners, all',
                    collate   => 'Real-game corners, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/small-pig-snout',
                    text      => 'Small pig snout',
                    collate   => 'Real-game corners, pig snout, 1',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/big-pig-snout',
                    text      => 'Big pig snout',
                    collate   => 'Real-game corners, pig snout, 2',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/rectangular-six',
                    text      => 'Rectangular six in the corner',
                    collate   => 'Real-game corners, rectangular six',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/l-group',
                    text      => 'L-group',
                    collate   => 'Real-game corners, l group, 1',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/long-l-group',
                    text      => 'Long L-group',
                    collate   => 'Real-game corners, l group, 2',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/corner/carpenters-square',
                    text      => "Carpenter's square",
                    collate   => "Real-game corners, carpenter's square",
                    thumbnail => $FILTER,
                },

                # Real-game sides
                {   filter    => '@tsumego/real/side',
                    text      => 'Real-game sides, All',
                    collate   => 'Real-game sides, aaa',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/side/notcher',
                    text      => 'Notchers, all',
                    collate   => 'Real-game sides, notchers, all',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/side/notcher and #status',
                    text      => 'Notchers, status',
                    collate   => 'Real-game sides, notchers, status',
                    thumbnail => $FILTER,
                },
                {   filter    => '@notcher/length/1',
                    text      => 'Notchers, one-space',
                    collate   => 'Real-game sides, notchers, 1-space',
                    thumbnail => $FILTER,
                },
                {   filter    => '@notcher/length/2',
                    text      => 'Notchers, two-space',
                    collate   => 'Real-game sides, notchers, 2-space',
                    thumbnail => $FILTER,
                },
                {   filter    => '@notcher/length/3',
                    text      => 'Notchers, three-space',
                    collate   => 'Real-game sides, notchers, 3-space',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/side/door',
                    text      => 'Door group',
                    collate   => 'Real-game sides, door group',
                    thumbnail => $FILTER,
                },
                {   filter    => '@tsumego/real/side/comb',
                    text      => 'Comb formation',
                    collate   => 'Real-game sides, comb',
                    thumbnail => $FILTER,
                },
            ]
        },
        {   text   => 'Capturing race',
            topics => [
                {   filter    => '#capturing_race',
                    text      => 'All',
                    rel_text  => 'Capturing race, all',
                    thumbnail => $FILTER,
                },
                {   filter    => '#extending_liberties',
                    text      => 'Extending liberties',
                    rel_text  => 'Capturing race, extending liberties',
                    thumbnail => $FILTER,
                },
                {   filter    => '#reducing_liberties',
                    text      => 'Reducing liberties',
                    rel_text  => 'Capturing race, reducing liberties',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capturing_race_ko',
                    text      => 'Ko',
                    rel_text  => 'Capturing race, ko',
                    thumbnail => $FILTER,
                },
                {   filter    => '#capturing_race_seki',
                    text      => 'Seki',
                    rel_text  => 'Capturing race, seki',
                    thumbnail => $FILTER,
                },
                {   filter    => '#one_eye_no_eye',
                    text      => 'Eye vs. no eye',
                    rel_text  => 'Capturing race, eye vs. no eye',
                    thumbnail => $FILTER,
                },
                {   filter    => '#destroying_one_eye',
                    text      => 'Destroying one eye',
                    rel_text  => 'Capturing race, destroying one eye',
                    thumbnail => $FILTER,
                }
            ]
        },
        {   topics => [
                {   filter    => '@joseki/33/44',
                    text      => '3-3',
                    rel_text  => '3-3, 4-4 cover',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/33/approach',
                    text      => '3-3',
                    rel_text  => '3-3, side approach',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter => '@joseki/34/1lap/diag/3lxt',
                    text   => '3-4, Shusaku diagonal',
                    rel_text =>
                      "3-4, knight's approach, Shusaku's diagonal, three-space low extension",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1lap/1kxt and not @1kxt/attach-inside-to-corner',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, knight's defense, not 3-3",
                    collate   => $FILTER,
                    thumbnail => 'joseki-34-1lap-1kxt-not-33.png',
                },
                {   filter    => '@joseki/34/1lap/1kxt/attach-inside-to-corner',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, knight's defense, 3-3",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1lap/1hp',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, one-space high pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1lap/1lp',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, one-space low pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1lap/2hp',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, two-space high pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1lap/tenuki/3lap',
                    text      => '3-4',
                    rel_text  => "3-4, knight's approach, tenuki, three-space low approach",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1hp',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space high pincer',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lp/attach-inside-to-corner/wedge',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space low pincer, 3-3, wedge',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lp/attach-inside-to-corner/hane',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space low pincer, 3-3, hane',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter => '@joseki/34/1hap/1lp/attach-inside-to-corner/2lxt',
                    text   => '3-4',
                    rel_text =>
                      '3-4, one-space approach, one-space low pincer, 3-3, two-space extension',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lp/diag-to-pincer',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space low pincer, diagonal',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lp/jump-descent',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space low pincer, jump descent',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lp/knight-to-corner',
                    text      => '3-4',
                    rel_text  => "3-4, one-space approach, one-space low pincer, knight's cover",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/1lxt',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space extension',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/2hp',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, one-space high pincer',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/attach-inside/hane',
                    text      => '3-4',
                    rel_text  => '3-4, one-space approach, inside attachment, hane',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/attach-inside/avalanche/small',
                    text      => '3-4',
                    rel_text  => '3-4, small avalanche',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/1hap/attach-inside/avalanche/large',
                    text      => '3-4',
                    rel_text  => '3-4, large avalanche',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/2lap/1hs',
                    text      => '3-4',
                    rel_text  => "3-4, large knight's approach, high enclosure",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/2lap/1lp',
                    text      => '3-4',
                    rel_text  => "3-4, large knight's approach, one-space low pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/34/2hap/tenuki/attach-inside-to-corner',
                    text      => '3-4',
                    rel_text  => '3-4, two-space approach, tenuki, 3-3',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/1lp',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, one-space low pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/1hp',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, one-space high pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/33',
                    text      => '4-4',
                    rel_text  => '4-4, 3-3 invasion',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/1hxt',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, knight's extension",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/1lxt',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, one-space extension",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/2hp',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, two-space high pincer",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter =>
                      '@joseki/44/1lap/tenuki/1lap or @joseki/44/1lap/1lp/1lap or @joseki/44/1lap/2hp/1lap',
                    text      => '4-4',
                    rel_text  => "4-4, double knight's approach",
                    collate   => $FILTER,
                    thumbnail => 'joseki-44-double-knight-approach.png',
                },
                {   filter    => '@joseki/44/1lap/attach-extend',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, attach-extend",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/44/1lap/diag',
                    text      => '4-4',
                    rel_text  => "4-4, knight's approach, Takemiya diagonal",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/54/34/attach-inside-to-corner',
                    text      => '5-4',
                    rel_text  => '5-4, 3-4, 3-3 attachment',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/53/34/knights-cover',
                    text      => '5-3',
                    rel_text  => "5-3, 3-4, knight's cover",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@joseki/53/34/large-knights-cover',
                    text      => '5-3',
                    rel_text  => "5-3, 3-4, large knight's cover",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                }
            ],
            text => 'Joseki',
        },
        {   topics => [
                {   filter    => '@enclosure/34/1hs',
                    text      => '3-4',
                    rel_text  => '3-4, one-space enclosure',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/34/2ls',
                    text      => '3-4',
                    rel_text  => "3-4, large knight's enclosure",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/44/1ls',
                    text      => '4-4',
                    rel_text  => "4-4, knight's enclosure",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/44/1ls/6lxt',
                    text      => '4-4',
                    rel_text  => "4-4, knight's enclosure plus six-space low extension",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/44/2ls',
                    text      => '4-4',
                    rel_text  => "4-4, large knight's enclosure",
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/44/5hxt',
                    text      => '4-4',
                    rel_text  => '4-4, five-space high wing',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                },
                {   filter    => '@enclosure/44/5lxt',
                    text      => '4-4',
                    rel_text  => '4-4, five-space low wing',
                    collate   => $FILTER,
                    thumbnail => $FILTER,
                }
            ],
            text => 'Enclosures',
        },
        {   topics => [
                {   filter    => '#question',
                    text      => 'Question-and-answer',
                    thumbnail => $FILTER,
                },
                {   filter    => '#show_choices',
                    text      => 'Show next move choices',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rate_choices',
                    text      => 'Rate multiple choices',
                    thumbnail => $FILTER,
                },
                {   filter    => '#multiple_choice',
                    text      => 'Multiple choice',
                    thumbnail => $FILTER,
                },
                {   filter    => '#copy and @joseki',
                    text      => 'Copy joseki',
                    thumbnail => $FILTER,
                },
                {   filter    => '#status',
                    text      => 'Life-and-death status',
                    thumbnail => $FILTER,
                },
                {   filter    => '#sujiba',
                    text      => 'Sujiba theory',
                    thumbnail => $FILTER,
                },
                {   filter    => '#counting_score',
                    text      => 'Count the score',
                    thumbnail => $FILTER,
                },
                {   filter    => '#calculating_move_value',
                    text      => "Calculate a move's value",
                    thumbnail => $FILTER,
                },
                {   filter    => '#debug',
                    text      => 'Debug',
                    thumbnail => $FILTER,
                }
            ],
            text => 'Tasks',
        },
        {   topics => [
                {   filter    => '#rank_intro',
                    text      => 'Introductory',
                    rel_text  => 'Introductory Problems',
                    collate   => '0',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rank_elementary',
                    text      => 'Elementary',
                    rel_text  => 'Elementary Problems',
                    collate   => '1',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rank_intermediate',
                    text      => 'Intermediate',
                    rel_text  => 'Intermediate Problems',
                    collate   => '2',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rank_advanced',
                    text      => 'Advanced',
                    rel_text  => 'Advanced Problems',
                    collate   => '3',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rank_low_dan',
                    text      => 'Low-dan',
                    rel_text  => 'Low-dan Problems',
                    collate   => '4',
                    thumbnail => $FILTER,
                },
                {   filter    => '#rank_high_dan',
                    text      => 'High-dan',
                    rel_text  => 'High-dan Problems',
                    collate   => '5',
                    thumbnail => $FILTER,
                },
            ],
            text => 'By Level',
        },
        {   text   => 'Games',
            topics => [
                {   filter    => '#progame',
                    text      => 'Professional games',
                    thumbnail => $FILTER,
                },
                {   filter    => '#game',
                    text      => 'Any real game',
                    thumbnail => $FILTER,
                }
            ]
        },
        {   text   => 'Yunguseng Dojang',
            topics => [
                {   filter => '@yunguseng-dojang/lectures/09/1',
                    text =>
                      "S09 lecture 1: Across attach; Break the dog's face; Indirect defense (Local Technique)",
                    rel_text  => 'S09 lecture 1',
                    thumbnail => $FILTER,
                },
                {   filter    => '@yunguseng-dojang/lectures/26/1',
                    text      => 'S26 lecture 1: Pinch (Local Technique)',
                    thumbnail => $FILTER,
                },
                {   filter    => '@yunguseng-dojang/lectures/26/3',
                    text      => 'S26 lecture 3: Kick and jump (Pattern)',
                    thumbnail => $FILTER,
                },
            ]
        },
        {   text => 'Old Classic Books',

            # Old classics don't have @p/ refs and so are public.
            topics => [
                {   text      => 'Gokyo Shumyo',
                    filter    => '@gokyo-shumyo',
                    thumbnail => $FILTER,
                    subsets   => [
                        {   text     => 'Living',
                            with_ref => 'gokyo-shumyo/live',
                        },
                        {   text     => 'Killing',
                            with_ref => 'gokyo-shumyo/kill',
                        },
                        {   text     => 'Ko',
                            with_ref => 'gokyo-shumyo/ko',
                        },
                        {   text     => 'Capturing race',
                            with_ref => 'gokyo-shumyo/semeai',
                        },
                        {   text     => 'Connect and die',
                            with_ref => 'gokyo-shumyo/oiotoshi',
                        },
                        {   text     => 'Connecting',
                            with_ref => 'gokyo-shumyo/watari',
                        },
                        {   text     => 'Wedge and others',
                            with_ref => 'gokyo-shumyo/warikomi-nado',
                        },
                        {   text     => "ツヅキ",
                            with_ref => 'gokyo-shumyo/tsuduki',
                        },
                        {   text     => 'Cut',
                            with_ref => 'gokyo-shumyo/kiri',
                        },
                        {   text     => 'Ladder',
                            with_ref => 'gokyo-shumyo/shichou',
                        },
                    ],
                },
                {   filter    => '@kanzufu',
                    text      => 'Kanzufu',
                    thumbnail => $FILTER,
                    subsets   => [
                        {   text     => 'Attack and Defense',
                            with_ref => 'kanzufu/attack-defense',
                        },
                        {   text     => 'Technique',
                            with_ref => 'kanzufu/technique',
                        },
                        {   text     => 'Tesuji',
                            with_ref => 'kanzufu/tesuji',
                        },
                        {   text     => 'Connection',
                            with_ref => 'kanzufu/connection',
                        },
                        {   text     => 'Life-and-death',
                            with_ref => 'kanzufu/life-and-death',
                        },
                        {   text     => 'Endgame',
                            with_ref => 'kanzufu/endgame',
                        },
                    ],
                },
                {   filter    => '@gengen-gokyo',
                    text      => 'Gengen Gokyo',
                    thumbnail => $FILTER,
                },
                {   filter    => '@shikatsu-myoki',
                    text      => 'Shikatsu Myoki',
                    thumbnail => $FILTER,
                },
                {   filter    => '@igo-hatsuyoron',
                    text      => 'Igo Hatsuyoron',
                    thumbnail => $FILTER,
                },
                {   filter    => '@gokyo-seimyo',
                    text      => 'Gokyo Seimyo',
                    thumbnail => $FILTER,
                },
                {   filter    => '@genran',
                    text      => 'Genran',
                    thumbnail => $FILTER,
                }
            ]
        },
    );
    return @menu;
}

# support some computed properties to avoid duplication and clutter
sub handle_computed_properties_for_section ($section) {
    for my $topic ($section->{topics}->@*) {
        if (defined($topic->{collate}) && $topic->{collate} eq $FILTER) {
            $topic->{collate} = $topic->{filter};
        }
        if (defined($topic->{thumbnail}) && $topic->{thumbnail} eq $FILTER) {

            # e.g., '@joseki/33/approach' becomes 'joseki-33-approach.png'
            $topic->{thumbnail} = "$topic->{filter}.png" =~ s/[\#\@]//gr =~ s![ _/]!-!gr;
        }
        if (defined $topic->{subsets}) {
            for my $subset ($topic->{subsets}->@*) {
                my $s = sprintf '%s %s %s %s',
                  map { $_ // 'undef' }
                  $subset->@{qw(with_ref without_ref with_tag without_tag)};
                $subset->{id} = utf8_sha1_hex($s);
            }
        }
    }
}
1;
