package GoGameTools::Porcelain::SiteGenData;
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::JSON;
use GoGameTools::Parser::FilterQuery;
use Path::Tiny;
use Digest::SHA qw(sha1_hex);
use utf8;
use GoGameTools::Class qw($delete_metadata $no_permalinks @menu);

sub run ($self) {
    return (
        sub ($collection) {

            # munge the SGJ objects so they look like eval_query() expects
            my (%problems_with_collection_id, %topic_index);
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{problem_id} = utf8_sha1_hex($sgj_obj->{sgf})
                  unless $self->no_permalinks;
                $sgj_obj->{collection_id} =
                  utf8_sha1_hex(sprintf '%s %s', $sgj_obj->{metadata}->@{qw(filename index)});
                $sgj_obj->{topics} = [];
                $sgj_obj->{vars}   = query_vars_from_sgj($sgj_obj);
                push @{ $problems_with_collection_id{ $sgj_obj->{collection_id} } //= [] },
                  $sgj_obj;
            }

            # concatenate the lists from all menu locations
            my @sections = (
                get_basic_menu(), map { json_decode(path($_)->slurp_utf8)->@* } $self->menu->@*
            );

            # For each topic, find the problems matching the topic's filter
            # expression. Store them with the topic.
            #
            # @result_sections and @result_topics_for_section are intermediate variables so
            # we can only take those sections and topics that actually contain problems.
            my @result_sections;
            for my $section (@sections) {
                my @result_topics_for_section;
                for my $topic ($section->{topics}->@*) {
                    my $expr = parse_filter_query($topic->{filter})
                      // die "can't parse filter query $topic->{filter}\n";
                    $topic->{problems} =
                      [ grep { eval_query(expr => $expr, vars => $_->{vars}) } $collection->@* ];
                    next unless $topic->{problems}->@*;

                    # The filename that the topic's problem collection will be written to.
                    $topic->{filename} = $topic->{filter} =~ s/\W+/-/gr =~ s/^-|-$//gr;

                    # When a problem is displayed, we want to show links to topics where
                    # this problem occurs. So build up a topic index that contains the
                    # button title and the topic's collection filename.
                    my %topic_for_index = $topic->%*;
                    $topic_for_index{count} = scalar($topic_for_index{problems}->@*);
                    delete $topic_for_index{problems};
                    $topic_index{ $topic->{filename} } = \%topic_for_index;

                    # For each problem in the current topic's collection, remember that
                    # these problems occurred in this topic. So at the end of the loop each
                    # problem contains a list of all the topics it occurs in.
                    push $_->{topics}->@*, $topic->{filename} for $topic->{problems}->@*;
                    push @result_topics_for_section, $topic;
                }
                if (@result_topics_for_section) {
                    $section->{topics} = \@result_topics_for_section;
                    push @result_sections, $section;
                }
            }
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{related_positions} =
                  scalar($problems_with_collection_id{ $sgj_obj->{collection_id} }->@*);

                # delete things that the site doesn't need
                delete $sgj_obj->{$_} for qw(game_info vars);
                delete $sgj_obj->{metadata}{input_filename};
                delete $sgj_obj->{metadata} if $self->delete_metadata;
            }

            # delete entries from the topic index that don't have problems
            my @empty_topic_index_keys;
            while (my ($k, $v) = each %topic_index) {
                push @empty_topic_index_keys, $k if $v->{count} == 0;
            }
            delete @topic_index{@empty_topic_index_keys};
            return +{
                menu             => \@result_sections,
                by_collection_id => \%problems_with_collection_id,
                topic_index      => \%topic_index,
                full_collection  => $collection,
            };
        }
    );
}

# sha1_hex() can't deal with Unicode, so this version converts it to bytes
sub utf8_sha1_hex ($data) {
    utf8::encode($data);
    return sha1_hex($data);
}

sub get_basic_menu {
    my @menu = (
        {   text => 'Old Classic Books',

            # Old classics don't have @p/ refs and so are public.
            topics => [
                {   text      => 'Gokyo Shumyo',
                    filter    => '@gokyo-shumyo',
                    thumbnail => 'gokyo-shumyo.png',
                },
                {   text      => 'Kanzufu',
                    filter    => '@kanzufu',
                    thumbnail => 'kanzufu.png',
                },
                {   filter    => '@gengen-gokyo',
                    text      => 'Gengen Gokyo',
                    thumbnail => 'gengen-gokyo.png',
                },
                {   filter    => '@shikatsu-myoki',
                    text      => 'Shikatsu Myoki',
                    thumbnail => 'shikatu-myoki.png',
                },
                {   text      => 'Igo Hatsuyoron',
                    filter    => '@igo-hatsuyoron',
                    thumbnail => 'igo-hatsuyoron.png',
                },
                {   text      => 'Gokyo Seimyo',
                    filter    => '@gokyo-seimyo',
                    thumbnail => 'gokyo-seimyo.png',
                },
                {   text      => 'Genran',
                    filter    => '@genran',
                    thumbnail => 'genran.png',
                }
            ]
        },
        {   text   => 'Books',
            topics => [
                {   filter    => '@p/y18',
                    text      => 'Rescue and Capture',
                    thumbnail => 'y18-rescue-and-capture.jpg',
                },
                {   filter    => '@p/k12',
                    text      => 'Tesuji (James Davies)',
                    thumbnail => 'k12-tesuji.jpg',
                },
                {   filter    => '@p/k56',
                    text      => 'Get Strong at Tesuji',
                    thumbnail => 'k56-get-strong-at-tesuji.jpg',
                },
                {   filter    => '@p/tesuji-daijiten',
                    text      => '手筋大事典',
                    thumbnail => 'tesuji-daijiten.jpg',
                },
                {   filter    => '@p/ishi-no-renraku-training-270',
                    text      => '石の連絡トレーニング２７０',
                    thumbnail => 'ishi-no-renraku-training-270.jpg',
                },
                {   filter    => '@p/1-geup-eui-subeob',
                    text      => '1급의 수법',
                    thumbnail => '1-geup-eui-subeob.jpg',
                },
                {   filter    => '@p/hyeondae-jungban-sajeon',
                    text      => '현대 중반 사전',
                    thumbnail => 'hyeondae-jungban-sajeon.jpg',
                },
                {   filter    => '@p/go-seigen-tsumego',
                    text      => '吳清源詰碁',
                    thumbnail => 'go-seigen-tsumego.jpg',
                },
                {   filter    => '@p/minna-no-tsumego',
                    text      => 'みんなの詰碁',
                    thumbnail => 'minna-no-tsumego.jpg',
                },
                {   filter    => '@p/k48',
                    text      => 'Graded Go Problems 3',
                    thumbnail => 'k48-graded-go-problems-3.jpg',
                },

                # Dictionary of Basic Tesuji 1 - Attacking
                {   filter    => '@p/dictionary-of-basic-tesuji/1',
                    text      => 'Dictionary of Basic Tesuji 1',
                    thumbnail => 'dictionary-of-basic-tesuji-1.jpg',
                },
                {   filter    => '@p/dictionary-of-basic-tesuji/2',
                    text      => 'Dictionary of Basic Tesuji 2',
                    thumbnail => 'dictionary-of-basic-tesuji-2.jpg',
                },
                {   filter    => '@p/dictionary-of-basic-tesuji/3',
                    text      => 'Dictionary of Basic Tesuji 3',
                    thumbnail => 'dictionary-of-basic-tesuji-3.jpg',
                },
                {   filter    => '@p/dictionary-of-basic-tesuji/4',
                    text      => 'Dictionary of Basic Tesuji 4',
                    thumbnail => 'dictionary-of-basic-tesuji-4.jpg',
                },

                # Cho Chikun's Encyclopedia of Life-and-Death
                {   filter    => '@p/cho-chikun-encyclopedia-of-life-and-death/0',
                    text      => '趙治勲死活大百科 0',
                    thumbnail => 'cho-chikun-encyclopedia-of-life-and-death-0.jpg',
                },
                {   filter    => '@p/cho-chikun-encyclopedia-of-life-and-death/1',
                    text      => '趙治勲死活大百科 1',
                    thumbnail => 'cho-chikun-encyclopedia-of-life-and-death-1.jpg',
                },
                {   filter    => '@p/cho-chikun-encyclopedia-of-life-and-death/2',
                    text      => '趙治勲死活大百科 2',
                    thumbnail => 'cho-chikun-encyclopedia-of-life-and-death-2.jpg',
                },
                {   filter    => '@p/cho-chikun-encyclopedia-of-life-and-death/3',
                    text      => '趙治勲死活大百科 3',
                    thumbnail => 'cho-chikun-encyclopedia-of-life-and-death-3.jpg',
                },

                # Segoe Kensaku's 手筋事典
                {   filter    => '@p/segoe-kensaku-tesuji-jiten/rank/A',
                    text      => '手筋事典 A',
                    thumbnail => 'segoe-kensaku-tesuji-jiten.jpg',
                },
                {   filter    => '@p/segoe-kensaku-tesuji-jiten/rank/B',
                    text      => '手筋事典 B',
                    thumbnail => 'segoe-kensaku-tesuji-jiten.jpg',
                },
                {   filter    => '@p/segoe-kensaku-tesuji-jiten/rank/C',
                    text      => '手筋事典 C',
                    thumbnail => 'segoe-kensaku-tesuji-jiten.jpg',
                },

                # 一手できまる手
                {   filter    => '@p/itte-de-kimaru-tesuji',
                    text      => '一手できまる手筋',
                    thumbnail => 'itte-de-kimaru-tesuji.jpg',
                },

                # 李昌镐精讲围棋手筋
                (   map {
                        +{  filter    => "\@p/li-chang-ho-jingjiang-weiqi-shoujin/$_",
                            text      => "李昌镐精讲围棋手筋 $_",
                            thumbnail => 'li-chang-ho-jingjiang-weiqi-shoujin-$_.jpg',
                        }
                    } 1 .. 6
                ),

                # 李昌镐精讲围棋死活
                (   map {
                        +{  filter    => "\@p/li-chang-ho-jingjiang-weiqi-sihuo/$_",
                            text      => "李昌镐精讲围棋死活 $_",
                            thumbnail => 'li-chang-ho-jingjiang-weiqi-sihuo-$_.jpg',
                        }
                    } 1 .. 6
                ),

                # Weiqi Life-and-Death 1000 Problems
                {   filter    => '@p/weiqi-life-death-1000',
                    text      => 'Weiqi Life-and-Death 1000',
                    thumbnail => 'weiqi-life-death-1000.jpg',
                },

                # 어린이 바둑 수련장
                {   filter    => '@p/eorini-baduk-suryeonjang/2',
                    text      => '어린이 바둑 수련장 2',
                    thumbnail => 'eorini-baduk-suryeonjang-2.jpg',
                },
                {   filter    => '@p/eorini-baduk-suryeonjang/3',
                    text      => '어린이 바둑 수련장 3',
                    thumbnail => 'eorini-baduk-suryeonjang-3.jpg',
                },
                {   filter    => '@p/eorini-baduk-suryeonjang/4',
                    text      => '어린이 바둑 수련장 4',
                    thumbnail => 'eorini-baduk-suryeonjang-4.jpg',
                },
            ]
        },
        {   text   => 'Techniques',
            topics => [
                {   text      => 'Double atari',
                    filter    => '#double_atari',
                    thumbnail => 'double-atari.png',
                },
                {   text      => 'Counter-atari',
                    filter    => '#counteratari',
                    thumbnail => 'counteratari.png',
                },
                {   text      => 'Lining up',
                    filter    => '#narabi',
                    thumbnail => 'lining_up.png',
                },
                {   text      => 'Dent',
                    filter    => '#dent',
                    thumbnail => 'dent.png',
                },
                {   text      => 'Wedge',
                    filter    => '#wedge',
                    thumbnail => 'wedge.png',
                },
                {   text      => 'Bend-wedge',
                    filter    => '#bend_wedge',
                    thumbnail => 'bend-wedge.png',
                },
                {   text      => 'Clamp',
                    filter    => '#clamp',
                    thumbnail => 'clamp.png',
                },
                {   filter    => '#counterclamp',
                    text      => 'Counter-clamp',
                    thumbnail => 'counter-clamp.png',
                },
                {   text      => 'Hane and cut',
                    filter    => '#hane_and_cut',
                    thumbnail => 'hane-and-cut.png',
                },
                {   filter    => '#hane_and_nakade',
                    text      => 'Hane and nakade',
                    thumbnail => 'hane-and-nakade.png',
                },
                {   filter    => '#peep_and_cut',
                    text      => 'Peep and cut',
                    thumbnail => 'peep-and-cut.png',
                },
                {   filter    => '#push_and_cut',
                    text      => 'Push and cut',
                    thumbnail => 'push-and-cut.png',
                },
                {   filter    => '#push_and_backtrack',
                    text      => 'Push and backtrack',
                    thumbnail => 'push-and-backtrack.png',
                },
                {   filter    => '#jumping_over_wall',
                    text      => 'Jumping over the wall',
                    thumbnail => 'jumping-over-the-wall.png',
                },
                {   text      => 'Attach and draw back',
                    filter    => '#attach_and_draw_back',
                    thumbnail => 'attach-and-draw-back.png',
                },
                {   text      => 'Attach and extend',
                    filter    => '#attach_and_extend',
                    thumbnail => 'attach-and-extend.png',
                },
                {   text      => 'Attach and hane',
                    filter    => '#attach_and_hane',
                    thumbnail => 'attach-and-hane.png',
                },
                {   text      => 'Attach and crosscut',
                    filter    => '#attach_and_crosscut',
                    thumbnail => 'attach-and-crosscut.png',
                },
                {   filter    => '#attach_and_block',
                    text      => 'Attach and block',
                    thumbnail => 'attach-and-block.png',
                },
                {   text      => 'Attach and bulge',
                    filter    => '#attach_and_bulge',
                    thumbnail => 'attach-and-bulge.png',
                },
                {   filter    => '#push_and_placement',
                    text      => 'Push and placement',
                    thumbnail => 'push-and-placement.png',
                },
                {   text      => 'Clamp against an attachment',
                    filter    => '#clamp_against_attachment',
                    thumbnail => 'clamp-against-attachment.png',
                },
                {   filter    => '#elephant_eye',
                    text      => "Elephant's eye",
                    thumbnail => 'elephants-eye.png',
                },
                {   text      => 'Diagonal cover',
                    filter    => '#diagonal_cover',
                    thumbnail => 'diagonal-cover.png',
                },
                {   filter    => '#knights_cover',
                    text      => "Knight's cover",
                    thumbnail => 'knights-cover.png',
                },
                {   filter    => '#large_knights_cover',
                    text      => "Large knight's cover",
                    thumbnail => 'large-knights-cover.png',
                },
                {   filter    => '#shoulder_hit',
                    text      => 'Shoulder hit',
                    thumbnail => 'shoulder-hit.png',
                },
                {   text      => 'Shoulder cut',
                    filter    => '#shoulder_cut',
                    thumbnail => 'shoulder-cut.png',
                },
                {   filter    => '#jump_attachment',
                    text      => 'Jump-attachment',
                    thumbnail => 'jump-attachment.png',
                },
                {   text      => 'Nose attachment',
                    filter    => '#nose_attachment',
                    thumbnail => 'nose-attachment.png',
                },
                {   text      => 'Table attachment',
                    filter    => '#table_attachment',
                    thumbnail => 'table-attachment.png',
                },
                {   text      => 'Anti tower peep placement',
                    filter    => '#anti_tower_peep_placement',
                    thumbnail => 'anti-tower-peep-placement.png',
                },
                {   text      => 'Belly attachment',
                    filter    => '#belly_attachment',
                    thumbnail => 'belly-attachment.png',
                },
                {   text      => 'Armpit',
                    filter    => '#armpit',
                    thumbnail => 'armput.png',
                },
                {   filter    => '#ankle_hook',
                    text      => 'Ankle hook',
                    thumbnail => 'ankle-hook.png',
                },
                {   filter    => '#breaking_the_wing',
                    text      => 'Breaking the wing',
                    thumbnail => 'breaking-the-wing.png',
                },
                {   filter    => '#cap',
                    text      => 'Cap',
                    thumbnail => 'cap.png',
                },
                {   text      => 'Caterpillar connection',
                    filter    => '#caterpillar_connection',
                    thumbnail => 'caterpillar-connection.png',
                },
                {   filter    => '#cave',
                    text      => 'Cave',
                    thumbnail => 'cave.png',
                },
                {   filter    => '#cranes_nest',
                    text      => "Crane's nest",
                    thumbnail => 'cranes-nest.png',
                },
                {   text      => 'Driving',
                    filter    => '#driving',
                    thumbnail => 'driving.png',
                },
                {   text      => 'Dog leg',
                    filter    => '#dogleg',
                    thumbnail => 'dog-leg.png',
                },
                {   text      => 'Crawling under the door',
                    filter    => '#crawling_under_the_door',
                    thumbnail => 'crawling-under-the-door.png',
                },
                {   text      => 'Snapback, all',
                    filter    => '#snapback',
                    thumbnail => 'snapback.png',
                },
                {   text      => 'Double snapback',
                    filter    => '#double_snapback',
                    collate   => 'Snapback, double',
                    thumbnail => 'double-snapback.png',
                },
                {   text      => 'Double hane edge squeeze',
                    filter    => '#double_hane_edge_squeeze',
                    thumbnail => 'double-hane-edge-squeeze.png',
                },
                {   text      => 'Eiffel tower',
                    filter    => '#eiffel_tower',
                    thumbnail => 'eiffel-tower.png',
                },
                {   filter    => '#eternal_life',
                    text      => 'Eternal life',
                    thumbnail => 'eternal-life.png',
                },
                {   filter    => '#eye_in_the_stomach',
                    text      => 'Eye in the stomach',
                    thumbnail => 'eye-in-the-stomach.png',
                },
                {   filter    => '#flower_six',
                    text      => 'Flower six',
                    thumbnail => 'flower-six.png',
                },
                {   filter    => '#grappling_hook',
                    text      => 'Grappling hook',
                    thumbnail => 'grappling-hook.png',
                },
                {   filter    => '#hane_at_the_head',
                    text      => 'Hane at the head',
                    thumbnail => 'hane-at-the-head.png',
                },
                {   text      => 'Ladder',
                    filter    => '#ladder',
                    collate   => 'Ladder, aaa',
                    thumbnail => 'ladder.png',
                },
                {   filter    => '#spiral_ladder',
                    text      => 'Spiral ladder',
                    collate   => 'Ladder, spiral',
                    thumbnail => 'spiral-ladder.png',
                },
                {   filter    => '#double_ladder',
                    text      => 'Double ladder',
                    collate   => 'Ladder, double',
                    thumbnail => 'double-ladder.png',
                },
                {   text      => 'Squeezing',
                    filter    => '#squeezing',
                    thumbnail => 'squeezing.png',
                },
                {   text      => 'Loose ladder',
                    filter    => '#loose_ladder',
                    thumbnail => 'loose-ladder.png',
                },
                {   filter    => '#mouse_stealing_oil',
                    text      => 'Mouse stealing oil',
                    thumbnail => 'mouse-stealing-oil.png',
                },
                {   text      => 'Monkey jump',
                    filter    => '#monkey_jump',
                    thumbnail => 'monkey-jump.png',
                },
                {   text      => 'Net',
                    filter    => '#net',
                    collate   => 'Net, aaa',
                    thumbnail => 'net.png',
                },
                {   filter    => '#knights_net',
                    text      => "Knight's net",
                    collate   => 'Net, knights',
                    thumbnail => 'knights-net.png',
                },
                {   filter    => '#first_line_descent',
                    text      => 'Descending to the first line',
                    thumbnail => 'first-line-descent.png',
                },
                {   text      => 'Parallel bars',
                    filter    => '#parallel_bars',
                    thumbnail => 'parallel-bars.png',
                },
                {   filter    => '#rooster_on_one_leg',
                    text      => 'Rooster on one leg',
                    thumbnail => 'rooster-on-one-leg.png',
                },
                {   filter    => '#sacrifice_two',
                    text      => 'Sacrifice two stones',
                    thumbnail => 'sacrifice-two.png',
                },
                {   filter    => '#shimetsuke',
                    text      => 'Tightening',
                    thumbnail => 'shimetsuke.png',
                },
                {   text      => 'Stick connection',
                    filter    => '#stick_connection',
                    thumbnail => 'stick-connection.png',
                },
                {   text      => "Double knight's connection",
                    filter    => '#double_knights_connection',
                    thumbnail => 'double-knights-connection.png',
                },
                {   text      => 'Symmetry',
                    filter    => '#symmetry',
                    thumbnail => 'symmetry.png',
                },
                {   filter    => '#tanuki_belly',
                    text      => 'Tanuki drumming his belly',
                    thumbnail => 'tanuki-belly.png',
                },
                {   filter    => '#three_is_one',
                    text      => 'Three is one',
                    thumbnail => 'three-is-one.png',
                },
                {   filter    => '#tombstone',
                    text      => 'Tombstone',
                    thumbnail => 'tombstone.png',
                },
                {   filter    => '#pushing_twice_then_keima',
                    text      => 'Pushing twice, then keima',
                    thumbnail => 'pushing-twice-then-keima.png',
                },
                {   text      => 'Under the stones, then cut',
                    filter    => '#cut_under_the_stones',
                    thumbnail => 'under-the-stones-then-cut.png',
                },
                {   text      => 'Under the stones, then placement',
                    filter    => '#placement_under_the_stones',
                    thumbnail => 'under-the-stones-then-placement.png',
                },
                {   text      => 'Windmill',
                    filter    => '#windmill',
                    thumbnail => 'windmill.png',
                },
                {   text      => 'Ko lock',
                    filter    => '#ko_lock',
                    thumbnail => 'ko-lock.png',
                },
                {   text      => 'Connect and die',
                    filter    => '#connect_and_die',
                    thumbnail => 'connect-and-die.png',
                },
                {   text      => 'Elbow lock',
                    filter    => '#elbow_lock',
                    thumbnail => 'elblow-lock.png',
                },
                {   filter    => '#carpenters_connection',
                    text      => "Carpenter's square connection",
                    thumbnail => 'carpenters-square-connection.png',
                },
                {   filter    => '#guzumi',
                    text      => 'Good empty triangle',
                    thumbnail => 'guzumi.png',
                },
                {   text      => 'Cork in the bottle',
                    filter    => '#cork_in_the_bottle',
                    thumbnail => 'cork-in-the-bottle.png',
                },
                {   text      => 'Angle play',
                    filter    => '#kado',
                    thumbnail => 'angle-play.png',
                },
                {   filter    => '#crosscut',
                    text      => 'Crosscut',
                    thumbnail => 'crosscut.png',
                },
                {   filter    => '#peep',
                    text      => 'Peep',
                    collate   => 'Peep, aaa',
                    thumbnail => 'peep.png',
                },
                {   text      => 'Resisting a peep',
                    filter    => '#resisting_peep',
                    collate   => 'Peep, resisting',
                    thumbnail => 'resisting-peep.png',
                },
                {   filter    => '#preventing_bamboo',
                    text      => 'Preventing the bamboo',
                    thumbnail => 'preventing-the-bamboo.png',
                },
                {   text      => 'Cut to defend against a cut',
                    filter    => '#cut_to_defend_cut',
                    thumbnail => 'cut-to-defend-against-cut.png',
                },
                {   text      => "Extra-large knight's move",
                    filter    => '#daidaigeima',
                    thumbnail => 'extra-large-knights-move.png',
                },
                {   text      => 'Pushing from behind',
                    filter    => '#pushing_from_behind',
                    thumbnail => 'pushing-from-behind.png',
                },
                {   filter    => '#second_line_kosumi',
                    text      => 'Diagonal move on the second line',
                    thumbnail => 'second-line-kosumi.png',
                },
                {   text      => 'Capturing two stones, recapturing one',
                    filter    => '#two_recapture_one',
                    thumbnail => 'two-recapture-one.png',
                },
                {   text      => 'Capturing two stones, getting two eyes',
                    filter    => '#capturing_two_for_two_eyes',
                    thumbnail => 'capturing-two-for-two-eyes.png',
                },
                {   text      => 'Wedge to separate',
                    filter    => '#wedge_separate',
                    thumbnail => 'wedge-to-separate.png',
                },
                {   filter    => '#invading_3_extension',
                    text      => 'Invading a three-space extension',
                    thumbnail => 'invading-three-space-extension.png',
                },
                {   filter    => '#trumpet_connection',
                    text      => 'Trumpet connection',
                    thumbnail => 'trumpet-connection.png',
                },
                {   filter    => '#unstable_connection',
                    text      => 'Unstable connections',
                    thumbnail => 'unstable-connection.png',
                },
                {   filter    => '#cat_face',
                    text      => "Cat's face",
                    collate   => 'Face, cat',
                    thumbnail => 'cat-face.png',
                },
                {   filter    => '#dog_face',
                    text      => "Dog's face",
                    collate   => 'Face, dog',
                    thumbnail => 'dog-face.png',
                },
                {   filter    => '#breaking_dog_face',
                    text      => "Breaking the dog's face",
                    collate   => 'Face, dog, break',
                    thumbnail => 'breaking-the-dogs-face.png',
                },
                {   filter    => '#horse_face',
                    text      => "Horse's face",
                    collate   => 'Face, horse',
                    thumbnail => 'horse-face.png',
                },
                {   filter    => '#giraffe_face',
                    text      => "Giraffe's face",
                    collate   => 'Face, giraffe',
                    thumbnail => 'giraffe-face.png',
                },
                {   filter    => '#bumping',
                    text      => 'Bumping',
                    thumbnail => 'bumping.png',
                },
                {   filter    => '#flying_double_clamp',
                    text      => 'Flying double clamp',
                    thumbnail => 'flying-double-clamp.png',
                },
                {   filter    => '#throwing_in',
                    text      => 'Throwing in',
                    thumbnail => 'throwing-in.png',
                },
                {   filter    => '#crossing_the_lair',
                    text      => 'Crossing the Lair',
                    thumbnail => 'crossing-the-lair.png',
                },
                {   filter    => '#pinch',
                    text      => 'Pinch',
                    thumbnail => 'pinch.png',
                },
                {   filter    => '#braid',
                    text      => 'Braid',
                    thumbnail => 'braid.png',
                },
                {   filter    => '#first_line_empty_triangle',
                    text      => 'Empty triangle on the first line',
                    thumbnail => 'first-line-empty-triangle.png',
                },
                {   filter    => '#across_attach',
                    text      => 'Across attach',
                    thumbnail => 'across-attach.png',
                },
                {   filter    => '#rhombus_attach',
                    text      => 'Rhombus attach',
                    thumbnail => 'rhombus-attach.png',
                },
                {   filter    => '#diagonal_attachment',
                    text      => 'Diagonal attachment',
                    thumbnail => 'diagonal-attachment.png',
                },
                {   filter    => '#tigers_mouth',
                    text      => "Tiger's mouth",
                    thumbnail => 'tigers-mouth.png',
                },
                {   filter    => '#nobikiri',
                    text      => 'Stretching in',
                    thumbnail => 'nobikiri.png',
                },
                {   filter    => '#bad_sente',
                    text      => 'Bad sente',
                    thumbnail => 'bad-sente.png',
                }
            ]
        },
        {   text   => 'Opening',
            topics => [
                {   filter    => '#making_a_position',
                    text      => 'Making a position',
                    thumbnail => 'making-a-position.png',
                },
                {   text      => 'Extending',
                    filter    => '#extending',
                    thumbnail => 'extending.png',
                },
                {   filter    => '#drawing_near',
                    text      => 'Drawing near',
                    thumbnail => 'drawing-near.png',
                },
                {   text      => 'Checking extension',
                    filter    => '#checking_extension',
                    thumbnail => 'checking-extension.png',
                },
                {   filter    => '#enlarging',
                    text      => 'Enlarging',
                    thumbnail => 'enlarging.png',
                },
                {   text      => 'Making a triangular framework',
                    filter    => '#making_a_triangular_framework',
                    collate   => 'Framework, 3, making',
                    thumbnail => 'making-a-triangular-framework.png',
                },
                {   text      => 'Preventing a triangular framework',
                    filter    => '#preventing_a_triangular_framework',
                    collate   => 'Framework, 3, preventing',
                    thumbnail => 'preventing-a-triangular-framework.png',
                },
                {   text      => 'Making a rectangular framework',
                    filter    => '#making_a_rectangular_framework',
                    collate   => 'Framework, 4, making',
                    thumbnail => 'making-a-rectangular-framework.png',
                },
                {   text      => 'Enlarging while limiting',
                    filter    => '#enlarging_while_limiting',
                    thumbnail => 'enlarging-while-limiting.png',
                },
                {   text      => 'Reducing from above',
                    filter    => '#reducing_from_above',
                    thumbnail => 'reducing-from-above.png',
                },
                {   filter    => '#surrounding',
                    text      => 'Surrounding',
                    thumbnail => 'surrounding.png',
                },
                {   text      => 'Low chinese fuseki',
                    filter    => '@fuseki/low-chinese',
                    collate   => 'Fuseki, chinese, low',
                    thumbnail => 'low-chinese-fuseki.png',
                },
                {   filter    => '@fuseki/high-chinese',
                    text      => 'High chinese fuseki',
                    collate   => 'Fuseki, chinese, high',
                    thumbnail => 'high-chinese-fuseki.png',
                },
                {   filter    => '@fuseki/mini-chinese',
                    text      => 'Mini chinese fuseki',
                    collate   => 'Fuseki, chinese, mini',
                    thumbnail => 'mini-chinese-fuseki.png',
                },
                {   text      => 'Micro chinese fuseki',
                    filter    => '@fuseki/micro-chinese',
                    collate   => 'Fuseki, chinese, micro',
                    thumbnail => 'micro-chinese-fuseki.png',
                },
                {   filter    => '#kobayashi_fuseki',
                    text      => '@fuseki/kobayashi',
                    collate   => 'Fuseki, Kobayashi',
                    thumbnail => 'kobayashi-fuseki.png',
                },
                {   text      => 'Facing 3-4 points',
                    filter    => '@fuseki/facing-34',
                    collate   => 'Fuseki, 3-4, facing',
                    thumbnail => 'facing-3-4-points.png',
                },
                {   filter    => '@fuseki/opposing-34',
                    text      => 'Opposing 3-4 points',
                    collate   => 'Fuseki, 3-4, opposing',
                    thumbnail => 'opposing-3-4-points.png',
                },
                {   filter    => '@fuseki/nirensei',
                    text      => 'Nirensei',
                    collate   => 'Fuseki, star points, 2',
                    thumbnail => 'nirensei.png',
                },
                {   text      => 'Sanrensei',
                    filter    => '@fuseki/sanrensei',
                    collate   => 'Fuseki, star points, 3',
                    thumbnail => 'sanrensei.png',
                }
            ]
        },
        {   topics => [
                {   text      => 'Separating',
                    filter    => '#separating',
                    thumbnail => 'separating.png',
                },
                {   filter    => '#pressing_down',
                    text      => 'Pressing down',
                    thumbnail => 'pressing-down.png',
                },
                {   filter    => '#sealing_in',
                    text      => 'Sealing in',
                    thumbnail => 'sealing-in.png',
                },
                {   text      => 'Spoiling shape, all',
                    filter    => '#spoiling_shape',
                    collate   => 'Spoiling shape, aaa',
                    thumbnail => 'spoiling-shape.png',
                },
                {   filter    => '#forcing_into_empty_triangle and not #forcing_into_farmers_hat',
                    text      => 'Empty triangle',
                    collate   => 'Spoiling shape, empty triangle',
                    thumbnail => 'empty-triangle.png',
                },
                {   filter    => '#forcing_into_farmers_hat',
                    text      => "Farmer's hat",
                    collate   => "Spoiling shape, farmer's hat",
                    thumbnail => 'farmers-hat.png',
                },
                {   text      => 'Dumpling',
                    filter    => '#forcing_into_dumpling',
                    collate   => 'Spoiling shape, dumpling',
                    thumbnail => 'dumpling.png',
                },
                {   text      => 'Probing',
                    filter    => '#probing',
                    thumbnail => 'probing.png',
                },
                {   filter    => '#making_heavy',
                    text      => 'Making heavy',
                    thumbnail => 'making-heavy.png',
                },
                {   filter    => '#overconcentrating',
                    text      => 'Overconcentrating',
                    thumbnail => 'overconcentrating.png',
                },
                {   text      => 'Creating weaknesses',
                    filter    => '#creating_weaknesses',
                    collate   => 'Creating weaknesses, aaa',
                    thumbnail => 'creating-weaknesses.png',
                },
                {   text      => 'Creating cuts',
                    filter    => '#creating_cuts',
                    collate   => 'Creating weaknesses, cuts',
                    thumbnail => 'creating-cuts.png',
                },
                {   text      => 'Making double threats',
                    filter    => '#making_double_threats',
                    thumbnail => 'making-double-threats.png',
                },
                {   text      => 'Taking away the base',
                    filter    => '#taking_away_base',
                    thumbnail => 'taking-away-the-base.png',
                },
                {   filter    => '#capturing',
                    text      => 'Capturing',
                    thumbnail => 'capturing.png',
                },
                {   text      => 'Making territory',
                    filter    => '#making_territory',
                    thumbnail => 'making-territory.png',
                },
                {   filter    => '#intimidating_with_ko',
                    text      => 'Intimidating with ko',
                    thumbnail => 'intimidating-with-ko.png',
                },
                {   text      => 'Making a fist',
                    filter    => '#making_fist',
                    thumbnail => 'making-a-fist.png',
                },
                {   filter    => '#invading',
                    text      => 'Invading',
                    thumbnail => 'invading.png',
                },
                {   text      => 'Kikashi',
                    filter    => '#kikashi',
                    thumbnail => 'kikashi.png',
                },
                {   text      => 'Bullying',
                    filter    => '#bullying',
                    thumbnail => 'bullying.png',
                },
                {   filter    => '#capping',
                    text      => 'Capping',
                    thumbnail => 'capping.png',
                },
                {   text      => 'Leaning attack',
                    filter    => '#leaning_attack',
                    thumbnail => 'leaning-attack.png',
                },
                {   filter    => '#splitting_attack',
                    text      => 'Splitting attack',
                    thumbnail => 'splitting-attack.png',
                }
            ],
            text => 'Attacking',
        },
        {   topics => [
                {   text      => 'Connecting',
                    filter    => '#connecting',
                    thumbnail => 'connecting.png',
                },
                {   filter    => '#capturing_key_stones',
                    text      => 'Capturing key stones',
                    thumbnail => 'capturing-key-stones.png',
                },
                {   text      => 'Developing',
                    filter    => '#developing',
                    thumbnail => 'developing.png',
                },
                {   text      => 'Escaping',
                    filter    => '#escaping',
                    thumbnail => 'escaping.png',
                },
                {   text      => 'Making shape',
                    filter    => '#making_shape',
                    thumbnail => 'making-shape.png',
                },
                {   filter    => '#taking_sente',
                    text      => 'Taking sente',
                    thumbnail => 'taking-sente.png',
                },
                {   text      => 'Handling weak stones',
                    filter    => '#sabaki',
                    thumbnail => 'handling-weak-stones.png',
                },
                {   filter    => '#striking_back',
                    text      => 'Striking back',
                    thumbnail => 'striking-back.png',
                },
                {   text      => 'Defending against multiple threats',
                    filter    => '#defending_against_multiple_threats',
                    thumbnail => 'defending-against-multiple-threats.png',
                },
                {   text      => 'Solidifying the base',
                    filter    => '#solidifying_base',
                    thumbnail => 'solidifying-the-base.png',
                },
                {   filter    => '#defending_base',
                    text      => 'Defending the base',
                    thumbnail => 'defending-the-base.png',
                },
                {   filter    => '#linking_up',
                    text      => 'Linking up',
                    thumbnail => 'linking-up.png',
                },
                {   text      => 'Resisting with ko',
                    filter    => '#resisting_with_ko',
                    thumbnail => 'resisting-with-ko.png',
                },
                {   text      => 'Forcing before defending',
                    filter    => '#forcing_before_defending',
                    thumbnail => 'forcing-before-defending.png',
                },
                {   text      => 'Indirect defense',
                    filter    => '#indirect_defense',
                    thumbnail => 'indirect-defense.png',
                },
                {   filter    => '#refuting_overplay',
                    text      => 'Refuting an overplay',
                    thumbnail => 'refuting-overplay.png',
                },
                {   text      => 'Trick play',
                    filter    => '#trick_play',
                    thumbnail => 'trick-play.png',
                },
                {   text      => 'Denying kikashi',
                    filter    => '#deny_kikashi',
                    thumbnail => 'denying-kikashi.png',
                }
            ],
            text => 'Defending',
        },
        {   topics => [
                {   filter    => '#sacrificing_junk_stones',
                    text      => 'Sacrificing junk stones',
                    thumbnail => 'sacrificing-junk-stones.png',
                },
                {   filter    => '#chasing_junk_stones',
                    text      => 'Chasing junk stones',
                    thumbnail => 'chasing-junk-stones.png',
                },
                {   filter    => '#walking_ahead',
                    text      => 'Walking ahead',
                    thumbnail => 'walking-ahead.png',
                },
                {   text      => 'Pushing from weakness',
                    filter    => '#pushing_from_weak_area',
                    thumbnail => 'pushing-from-weakness.png',
                },
                {   text      => 'Choice of joseki',
                    filter    => '#joseki_choice',
                    thumbnail => 'choice-of-joseki.png',
                },
                {   text      => 'Direction of attack',
                    filter    => '#direction_of_attack',
                    thumbnail => 'direction-of-attack.png',
                },
                {   text      => 'Value of sides',
                    filter    => '#value_of_sides',
                    thumbnail => 'value-of-sides.png',
                },
                {   filter    => '#playing_away_from_thickness',
                    text      => 'Playing away from thickness',
                    thumbnail => 'playing-away-from-thickness.png',
                },
                {   filter    => '#avoiding_being_enclosed',
                    text      => 'Avoiding being enclosed',
                    thumbnail => 'avoiding-being-enclosed.png',
                },
                {   filter    => '#leaving_aji',
                    text      => 'Leaving aji',
                    thumbnail => 'leaving-aji.png',
                },
                {   filter    => '#good_ugly_keima_cut',
                    text      => 'Good ugly keima cut',
                    thumbnail => 'good-ugly-keima-cut.png',
                },
                {   filter    => '#tenuki',
                    text      => 'Tenuki',
                    thumbnail => 'tenuki.png',
                },
                {   filter    => '#running_battle',
                    text      => 'Running battle',
                    thumbnail => 'running-battle.png',
                },
                {   text      => 'Commanding the high point',
                    filter    => '#tennouzan',
                    thumbnail => 'commanding-the-high-point.png',
                },
                {   text      => 'Four cut groups',
                    filter    => '#crossfight',
                    thumbnail => 'four-cut-groups.png',
                }
            ],
            text => 'Strategy',
        },
        {   topics => [
                {   filter    => '#solidifying_base and #taking_away_base',
                    text      => 'Base of both sides',
                    thumbnail => 'base-of-both-sides.png',
                },
                {   filter    => '#handling_invasion',
                    text      => 'Handling an invasion',
                    thumbnail => 'handling-invasion.png',
                },
                {   filter    => '#speculative_invasion',
                    text      => 'Speculative invasion',
                    thumbnail => 'speculative-invasion.png',
                }
            ],
            text => 'Multiple objectives',
        },
        {   topics => [
                {   text      => 'Breaking in',
                    filter    => '#breaking_in',
                    thumbnail => 'breaking-in.png',
                },
                {   text      => 'Encroaching on territory',
                    filter    => '#encroaching',
                    collate   => 'Encroaching, doing',
                    thumbnail => 'encroaching-on-territory.png',
                },
                {   filter    => '#stopping_encroachments',
                    text      => 'Stopping encroachments',
                    collate   => 'Encroaching, stopping',
                    thumbnail => 'stopping-encroachments.png',
                },
                {   text      => 'Large yose',
                    filter    => '#large_yose',
                    thumbnail => 'large-yose.png',
                },
                {   text      => 'Threatening to kill',
                    filter    => '#threatening_to_kill',
                    thumbnail => 'threatening-to-kill.png',
                },
                {   filter    => '#forcing_removal',
                    text      => 'Forcing removal',
                    thumbnail => 'forcing-removal.png',
                },
                {   text      => 'Double endgame attacks',
                    filter    => '#double_endgame_attacks',
                    thumbnail => 'double-endgame-attacks.png',
                },
                {   filter    => '#double_endgame_defenses',
                    text      => 'Double endgame defenses',
                    thumbnail => 'double-endgame-defenses.png',
                },
                {   filter    => '#closing_in_sente',
                    text      => 'Closing boundaries in sente',
                    thumbnail => 'closing-in-sente.png',
                }
            ],
            text => 'Endgame',
        },
        {   text   => 'Life-and-death',
            topics => [

                # Real-game corners
                {   collate   => 'Real-game corners, aaa',
                    filter    => '@tsumego/real/corner',
                    text      => 'Real-game corners, all',
                    thumbnail => 'real-game-corners.png',
                },
                {   text      => 'Small pig snout',
                    filter    => '@tsumego/real/corner/small-pig-snout',
                    collate   => 'Real-game corners, pig snout, 1',
                    thumbnail => 'small-pig-snout.png',
                },
                {   filter    => '@tsumego/real/corner/big-pig-snout',
                    text      => 'Big pig snout',
                    collate   => 'Real-game corners, pig snout, 2',
                    thumbnail => 'big-pig-snout.png',
                },
                {   text      => 'Rectangular six in the corner',
                    filter    => '@tsumego/real/corner/rectangular-six',
                    collate   => 'Real-game corners, rectangular six',
                    thumbnail => 'rectangular-six-in-the-corner.png',
                },
                {   filter    => '@tsumego/real/corner/l-group',
                    text      => 'L-group',
                    collate   => 'Real-game corners, l group, 1',
                    thumbnail => 'l-group.png',
                },
                {   collate   => 'Real-game corners, l group, 2',
                    filter    => '@tsumego/real/corner/long-l-group',
                    text      => 'Long L-group',
                    thumbnail => 'long-l-group.png',
                },
                {   filter    => '@tsumego/real/corner/carpenters-square',
                    text      => "Carpenter's square",
                    collate   => "Real-game corners, carpenter's square",
                    thumbnail => 'catpenters-square.png',
                },

                # Real-game sides
                {   text      => 'Real-game sides, All',
                    filter    => '@tsumego/real/side',
                    collate   => 'Real-game sides, aaa',
                    thumbnail => 'real-game-sides.png',
                },
                {   text      => 'Notchers, all',
                    filter    => '@tsumego/real/side/notcher',
                    collate   => 'Real-game sides, notchers, all',
                    thumbnail => 'notchers.png',
                },
                {   text      => 'Notchers, status',
                    filter    => '@tsumego/real/side/notcher and #status',
                    collate   => 'Real-game sides, notchers, status',
                    thumbnail => 'notchers-status.png',
                },
                {   text      => 'Notchers, one-space',
                    filter    => '@notcher/length/1',
                    collate   => 'Real-game sides, notchers, 1-space',
                    thumbnail => 'notchers-1-space.png',
                },
                {   text      => 'Notchers, two-space',
                    filter    => '@notcher/length/2',
                    collate   => 'Real-game sides, notchers, 2-space',
                    thumbnail => 'notchers-2-space.png',
                },
                {   text      => 'Notchers, three-space',
                    filter    => '@notcher/length/3',
                    collate   => 'Real-game sides, notchers, 3-space',
                    thumbnail => 'notchers-3-space.png',
                },
                {   collate   => 'Real-game sides, door group',
                    filter    => '@tsumego/real/side/door',
                    text      => 'Door group',
                    thumbnail => 'door-group.png',
                },
                {   collate   => 'Real-game sides, comb',
                    filter    => '@tsumego/real/side/comb',
                    text      => 'Comb formation',
                    thumbnail => 'comb-formation.png',
                },

                # Making one eye
                {   collate   => 'Making one eye, 2',
                    filter    => '@tsumego/making-one-eye/other',
                    text      => 'Making one eye, other',
                    thumbnail => 'making-one-eye-other.png',
                },
                {   collate   => 'Making one eye, 1',
                    filter    => '@tsumego/making-one-eye/second-line-shape',
                    text      => 'Making one eye, second-line shapes',
                    thumbnail => 'making-one-eye-second-line-shapes.png',
                },

                # Living
                {   collate   => 'Living, aaa',
                    text      => 'Living, all',
                    filter    => '#living',
                    thumbnail => 'living.png',
                },
                {   text      => 'Living by securing eye shape',
                    filter    => '#securing_eye_shape',
                    collate   => 'Living, securing eye shape',
                    thumbnail => 'securing-eye-shape.png',
                },
                {   filter    => '#enlarging_eye_space',
                    text      => 'Living by enlarging eye space',
                    collate   => 'Living, enlarging eye space',
                    thumbnail => 'enlarging-eye-space.png',
                },
                {   collate   => 'Living, false eyes',
                    filter    => '#living_with_false_eyes',
                    text      => 'Living with false eyes',
                    thumbnail => 'living-with-false-eyes.png',
                },
                {   collate   => 'Living, seki',
                    filter    => '#living_with_seki',
                    text      => 'Living with seki',
                    thumbnail => 'living-with-seki.png',
                },
                {   collate   => 'Living, squashing',
                    filter    => '#squashing',
                    text      => 'Living by squashing',
                    thumbnail => 'squashing.png',
                },
                {   collate   => 'Living, ko, 1',
                    text      => 'Living with Ko',
                    filter    => '#living_with_ko',
                    thumbnail => 'living-with-ko.png',
                },
                {   collate   => 'Living, ko, 2',
                    text      => 'Living with double ko',
                    filter    => '#living_with_double_ko',
                    thumbnail => 'living-with-double-ko.png',
                },

                # Killing
                {   collate   => 'Killing, aaa',
                    filter    => '#killing',
                    text      => 'Killing all',
                    thumbnail => 'killing.png',
                },
                {   filter    => '#nakade',
                    text      => 'Killing with nakade',
                    collate   => 'Killing, nakade',
                    thumbnail => 'nakade.png',
                },
                {   text      => 'Bent four in the corner',
                    filter    => '#bent_four_in_the_corner',
                    collate   => 'Killing, bent four in the corner',
                    thumbnail => 'bent-four-in-the-corner.png',
                },
                {   collate   => 'Killing, false eye',
                    filter    => '#making_a_false_eye',
                    text      => 'Killing by making a false eye',
                    thumbnail => 'making-a-false-eye.png',
                },
                {   filter    => '#killing_with_ko',
                    text      => 'Killing with ko',
                    collate   => 'Killing, ko, 1',
                    thumbnail => 'killing-with-ko.png',
                },
                {   collate   => 'Killing, ko, 2',
                    filter    => '#killing_with_double_ko',
                    text      => 'Killing with double ko',
                    thumbnail => 'killing-with-double-ko.png',
                },
                {   filter    => '#ten_thousand_year_ko',
                    text      => '10,000 year ko',
                    collate   => 'Killing, ko, 3',
                    thumbnail => 'ten-thousand-year-ko.png',
                }
            ]
        },
        {   text   => 'Capturing race',
            topics => [
                {   filter    => '#capturing_race',
                    text      => 'All',
                    rel_text  => 'Capturing race, all',
                    thumbnail => 'capturing-race.png',
                },
                {   text      => 'Extending liberties',
                    rel_text  => 'Capturing race, extending liberties',
                    filter    => '#extending_liberties',
                    thumbnail => 'extending-liberties.png',
                },
                {   text      => 'Reducing liberties',
                    rel_text  => 'Capturing race, reducing liberties',
                    filter    => '#reducing_liberties',
                    thumbnail => 'reducing-liberties.png',
                },
                {   text      => 'Ko',
                    rel_text  => 'Capturing race, ko',
                    filter    => '#capturing_race_ko',
                    thumbnail => 'capturing-race-ko.png',
                },
                {   text      => 'Seki',
                    rel_text  => 'Capturing race, seki',
                    filter    => '#capturing_race_seki',
                    thumbnail => 'capturing-race-seki.png',
                },
                {   filter    => '#one_eye_no_eye',
                    text      => 'Eye vs. no eye',
                    rel_text  => 'Capturing race, eye vs. no eye',
                    thumbnail => 'one-eye-no-eye.png',
                },
                {   text      => 'Destroying one eye',
                    rel_text  => 'Capturing race, destroying one eye',
                    filter    => '#destroying_one_eye',
                    thumbnail => 'destroying-one-eye.png',
                }
            ]
        },
        {   topics => [
                {   filter    => '@joseki/33/44',
                    text      => '3-3, 4-4 cover',
                    thumbnail => 'joseki-33-44.png',
                },
                {   text      => '3-3, side approach',
                    filter    => '@joseki/33/approach',
                    thumbnail => 'joseki-33-approach.png',
                },
                {   text   => "3-4, knight's approach, Shusaku's kosumi, three-space low extension",
                    filter => '@joseki/34/1lap/diag/3lxt',
                    thumbnail => 'joseki-34-1lap-diag-3lxt.png',
                },
                {   filter    => '@joseki/34/1lap/1kxt and not @1kxt/attach-inside-to-corner',
                    text      => "3-4, knight's approach, knight's defense, not 3-3",
                    thumbnail => '34-1lap-1kxt-not-33.png',
                },
                {   filter    => '@joseki/34/1lap/1kxt/attach-inside-to-corner',
                    text      => "3-4, knight's approach, knight's defense, 3-3",
                    thumbnail => 'joseki-34-1lap-1kxt-attach-inside-to-corner.png',
                },
                {   filter    => '@joseki/34/1lap/1hp',
                    text      => "3-4, knight's approach, one-space high pincer",
                    thumbnail => 'joseki-34-1lap-1hp.png',
                },
                {   text      => "3-4, knight's approach, one-space low pincer",
                    filter    => '@joseki/34/1lap/1lp',
                    thumbnail => 'joseki-34-lap-1lp.png',
                },
                {   text      => "3-4, knight's approach, two-space high pincer",
                    filter    => '@joseki/34/1lap/2hp',
                    thumbnail => 'joseki-34-1lap-2hp.png',
                },
                {   text      => "3-4, knight's approach, tenuki, three-space low approach",
                    filter    => '@joseki/34/1lap/tenuki/3lap',
                    thumbnail => 'joseki-34-1lap-tenuki-3lap.png',
                },
                {   text      => '3-4, one-space approach, one-space high pincer',
                    filter    => '@joseki/34/1hap/1hp',
                    thumbnail => 'joseki-34-1hap-1hp.png',
                },
                {   text      => '3-4, one-space approach, one-space low pincer, 3-3, wedge',
                    filter    => '@joseki/34/1hap/1lp/attach-inside-to-corner/wedge',
                    thumbnail => 'joseki-34-1hap-1lp-attach-inside-to-corner-wedge.png',
                },
                {   filter    => '@joseki/34/1hap/1lp/attach-inside-to-corner/hane',
                    text      => '3-4, one-space approach, one-space low pincer, 3-3, hane',
                    thumbnail => 'joseki-34-1hap-1lp-attach-inside-to-corner-hane.png',
                },
                {   filter => '@joseki/34/1hap/1lp/attach-inside-to-corner/2lxt',
                    text =>
                      '3-4, one-space approach, one-space low pincer, 3-3, two-space extension',
                    thumbnail => 'joseki-34-1hap-1lp-attach-inside-to-corner-2lxt.png',
                },
                {   text      => '3-4, one-space approach, one-space low pincer, kosumi',
                    filter    => '@joseki/34/1hap/1lp/diag-to-pincer',
                    thumbnail => 'joseki-34-1hap-1lp-diag-to-pincer.png',
                },
                {   filter    => '@joseki/34/1hap/1lp/jump-descent',
                    text      => '3-4, one-space approach, one-space low pincer, jump descent',
                    thumbnail => 'joseki-34-1hap-1lp-jump-descent.png',
                },
                {   text      => "3-4, one-space approach, one-space low pincer, knight's cover",
                    filter    => '@joseki/34/1hap/1lp/knight-to-corner',
                    thumbnail => 'joseki-34-1hap-1lp-knight-to-corner.png',
                },
                {   filter    => '@joseki/34/1hap/1lxt',
                    text      => '3-4, one-space approach, one-space extension',
                    thumbnail => 'joseki-34-1hap-1lxt.png',
                },
                {   filter    => '@joseki/34/1hap/2hp',
                    text      => '3-4, one-space approach, one-space high pincer',
                    thumbnail => 'joseki-34-1hap-2hp.png',
                },
                {   filter    => '@joseki/34/1hap/attach-inside/hane',
                    text      => '3-4, one-space approach, inside attachment, hane',
                    thumbnail => 'joseki-34-1hap-attach-inside-hane.png',
                },
                {   filter    => '@joseki/34/1hap/attach-inside/avalanche/small',
                    text      => '3-4, small avalanche',
                    collate   => '3-4, avalanche, small',
                    thumbnail => 'joseki-34-small-avalanche.png',
                },
                {   filter    => '@joseki/34/1hap/attach-inside/avalanche/large',
                    text      => '3-4, large avalanche',
                    collate   => '3-4, avalanche, large',
                    thumbnail => 'joseki-34-large-avalanche.png',
                },
                {   filter    => '@joseki/34/2lap/1hs',
                    text      => "3-4, large knight's approach, high shimari",
                    thumbnail => 'joseki-34-2lap-1hs.png',
                },
                {   filter    => '@joseki/34/2lap/1lp',
                    text      => "3-4, large knight's approach, one-space low pincer",
                    thumbnail => 'joseki-34-2lap-1lp.png',
                },
                {   text      => '3-4, two-space approach, tenuki, 3-3',
                    filter    => '@joseki/34/2hap/tenuki/attach-inside-to-corner',
                    thumbnail => 'joseki-34-2hap-tenuki-attach-inside-to-corner.png',
                },
                {   filter    => '@joseki/44/1lap/1lp',
                    text      => "4-4, knight's approach, one-space low pincer",
                    thumbnail => 'joseki-44-1lap-1lp.png',
                },
                {   filter    => '@joseki/44/1lap/1hp',
                    text      => "4-4, knight's approach, one-space high pincer",
                    thumbnail => 'joseki-44-1lap-1hp.png',
                },
                {   text      => '4-4, 3-3 invasion',
                    filter    => '@joseki/44/33',
                    thumbnail => 'joseki-44-33.png',
                },
                {   text      => "4-4, knight's approach, knight's extension",
                    filter    => '@joseki/44/1lap/1hxt',
                    thumbnail => 'joseki-44-1lap-1hxt.png',
                },
                {   filter    => '@joseki/44/1lap/1lxt',
                    text      => "4-4, knight's approach, one-space extension",
                    thumbnail => 'joseki-44-1lap-1lxt.png',
                },
                {   text      => "4-4, knight's approach, two-space high pincer",
                    filter    => '@joseki/44/1lap/2hp',
                    thumbnail => 'joseki-44-1lap-2hp.png',
                },
                {   text => "4-4, double knight's approach",
                    filter =>
                      '@joseki/44/1lap/tenuki/1lap or @joseki/44/1lap/1lp/1lap or @joseki/44/1lap/2hp/1lap',
                    thumbnail => 'joseki-44-double-knight-approach.png',
                },
                {   text      => "4-4, knight's approach, attach-extend",
                    filter    => '@joseki/44/1lap/attach-extend',
                    thumbnail => 'joseki-44-1lap-attach-extend.png',
                },
                {   text      => "4-4, knight's approach, Takemiya kosumi",
                    filter    => '@joseki/44/1lap/diag',
                    thumbnail => 'joseki-44-1lap-diag.png',
                },
                {   filter    => '@joseki/54/34/attach-inside-to-corner',
                    text      => '5-4, 3-4, 3-3 attachment',
                    thumbnail => 'joseki-54-34-attach-inside-to-corner.png',
                },
                {   text      => "5-3, 3-4, knight's cover",
                    filter    => '@joseki/53/34/knights-cover',
                    thumbnail => 'joseki-53-34-knights-cover.png',
                },
                {   text      => "5-3, 3-4, large knight's cover",
                    filter    => '@joseki/53/34/large-knights-cover',
                    thumbnail => 'joseki-53-34-large-knights-cover.png',
                }
            ],
            text => 'Joseki',
        },
        {   topics => [
                {   text      => '3-4, one-space shimari',
                    filter    => '@enclosure/34/1hs',
                    thumbnail => 'enclosure-34-1hs.png',
                },
                {   filter    => '@enclosure/34/2ls',
                    text      => "3-4, large knight's shimari",
                    thumbnail => 'enclosure-34-2ls.png',
                },
                {   text      => "4-4, knight's shimari",
                    filter    => '@enclosure/44/1ls',
                    thumbnail => 'enclosure-44-1ls.png',
                },
                {   text      => "4-4, knight's shimari plus six-space low extension",
                    filter    => '@enclosure/44/1ls/6lxt',
                    thumbnail => 'enclosure-44-1ls-6lxt.png',
                },
                {   filter    => '@enclosure/44/2ls',
                    text      => "4-4, large knight's shimari",
                    thumbnail => 'enclosure-44-2ls.png',
                },
                {   filter    => '@enclosure/44/5hxt',
                    text      => '4-4, five-space high wing',
                    thumbnail => 'enclosure-44-5hxt.png',
                },
                {   text      => '4-4, five-space low wing',
                    filter    => '@enclosure/44/5lxt',
                    thumbnail => 'enclosure-44-5lxt.png',
                }
            ],
            text => 'Enclosures',
        },
        {   topics => [
                {   filter    => '#question',
                    text      => 'Question-and-answer',
                    thumbnail => 'question-and-answer.png',
                },
                {   filter    => '#show_choices',
                    text      => 'Show choices for the next move',
                    thumbnail => 'show-choices.png',
                },
                {   filter    => '#rate_choices',
                    text      => 'Rate multiple choices',
                    thumbnail => 'rate-choices.png',
                },
                {   filter    => '#multiple_choice',
                    text      => 'Choose one of several moves',
                    thumbnail => 'multiple-choices.png',
                },
                {   filter    => '#copy and @joseki',
                    text      => 'Copy joseki',
                    thumbnail => 'copy-joseki.png',
                },
                {   filter    => '#status',
                    text      => 'Life-and-death status',
                    thumbnail => 'status.png',
                },
                {   text      => 'Sujiba theory',
                    filter    => '#sujiba',
                    thumbnail => 'sujiba-theory.png',
                },
                {   text      => 'Count the score',
                    filter    => '#counting_score',
                    thumbnail => 'count-the-score.png',
                },
                {   text      => "Calculate a move's value",
                    filter    => '#calculating_move_value',
                    thumbnail => 'calculating-move-value.png',
                },
                {   text      => 'Debug',
                    filter    => '#debug',
                    thumbnail => 'debug.png',
                }
            ],
            text => 'Tasks',
        },
        {   topics => [
                {   filter    => '#ddk3',
                    text      => '30k',
                    collate   => 'Level 0',
                    thumbnail => 'level-0.png',
                },
                {   filter    => '#ddk2',
                    text      => '29k-20k',
                    collate   => 'Level 1',
                    thumbnail => 'level-1.png',
                },
                {   filter    => '#ddk1',
                    text      => '19k-10k',
                    collate   => 'Level 2',
                    thumbnail => 'level-2.png',
                },
                {   filter    => '#lowsdk',
                    text      => '9k-5k',
                    collate   => 'Level 3',
                    thumbnail => 'level-3.png',
                },
                {   filter    => '#highsdk',
                    text      => '4k-1k',
                    collate   => 'Level 4',
                    thumbnail => 'level-4.png',
                },
                {   filter    => '#lowdan',
                    text      => '1d-4d',
                    collate   => 'Level 5',
                    thumbnail => 'level-5.png',
                },
                {   filter    => '#highdan',
                    text      => '5d-7d',
                    collate   => 'Level 6',
                    thumbnail => 'level-6.png',
                },
            ],
            text => 'By Level',
        },
        {   text   => 'Games',
            topics => [
                {   text      => 'Professional games',
                    filter    => '#progame',
                    thumbnail => 'pro-game.png',
                },
                {   text      => 'Any real game',
                    filter    => '#game',
                    thumbnail => 'any-game.png',
                }
            ]
        },
        {   text   => 'Yunguseng Dojang',
            topics => [
                {   text =>
                      "S09 lecture 1: Across attach; Break the dog's face; Indirect defense (Local Technique)",
                    rel_text  => 'S09 lecture 1',
                    filter    => '@yunguseng-dojang/lectures/09/1',
                    thumbnail => 'yd-lecture-09-1.png',
                },
                {   text      => 'S26 lecture 1: Pinch (Local Technique)',
                    filter    => '@yunguseng-dojang/lectures/26/1',
                    thumbnail => 'yd-lecture-26-1.png',
                },
                {   text      => 'S26 lecture 3: Kick and jump (Pattern)',
                    filter    => '@yunguseng-dojang/lectures/26/3',
                    thumbnail => 'yd-lecture-26-3.png',
                },
            ]
        },
    );
    return @menu;
}
1;
