package GoGameTools::Porcelain::SiteGenData;
use GoGameTools::features;
use GoGameTools::Util;
use GoGameTools::JSON;
use GoGameTools::Porcelain::Subsets;
use GoGameTools::Parser::FilterQuery;
use Path::Tiny;
use utf8;
use GoGameTools::Class qw($no_permalinks @menu);
my $FILTER = '$filter';

sub run ($self) {
    return (
        sub ($collection) {

            # munge the SGJ objects so they look like eval_query() expects
            my (%problems_with_collection_id, %topic_index);
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{problem_id} = utf8_sha1_hex($sgj_obj->{sgf})
                  unless $self->no_permalinks;
                $sgj_obj->{collection_id} =
                  utf8_sha1_hex(sprintf '%s %s', $sgj_obj->{metadata}->@{qw(filename index)});
                $sgj_obj->{topics} = [];
                $sgj_obj->{vars}   = query_vars_from_sgj($sgj_obj);
                push @{ $problems_with_collection_id{ $sgj_obj->{collection_id} } //= [] },
                  $sgj_obj;
            }

            # concatenate the lists from all menu locations
            my @sections = (get_basic_menu(), map { read_menu($_)->@* } $self->menu->@*);

            # For each topic, find the problems matching the topic's filter
            # expression. Store them with the topic.
            #
            # @result_sections and @result_topics_for_section are intermediate variables so
            # we can only take those sections and topics that actually contain problems.
            my @result_sections;
            for my $section (@sections) {
                my @result_topics_for_section;
                handle_computed_properties_for_section($section);
                for my $topic ($section->{topics}->@*) {

                    # find problems for this topic
                    my $problems = get_problems_for_subset($topic, $collection);
                    next unless $problems->@*;
                    $topic->{problems} = $problems;

                    # Handle subsets: determine how many problems are in each
                    # subset; skip subsets without problems.
                    if (defined $topic->{subsets}) {
                        for my $subset ($topic->{subsets}->@*) {
                            my $subset_problems = get_problems_for_subset($subset, $problems);
                            $subset->{count} = $subset_problems->@*;    # we only want the count
                        }

                        # remove subsets without problems
                        $topic->{subsets} = [ grep { $_->{count} > 0 } $topic->{subsets}->@* ];
                    }

                    # The filename that the topic's problem collection will be written to.
                    $topic->{filename} = $topic->{id};

                    # When a problem is displayed, we want to show links to topics where
                    # this problem occurs. So build up a topic index that contains the
                    # button title and the topic's collection filename.
                    my %topic_for_index = $topic->%*;
                    $topic_for_index{count} = scalar($topic_for_index{problems}->@*);
                    delete $topic_for_index{problems};
                    $topic_index{ $topic->{filename} } = \%topic_for_index;

                    # For each problem in the current topic's collection, remember that
                    # these problems occurred in this topic. So at the end of the loop each
                    # problem contains a list of all the topics it occurs in.
                    push $_->{topics}->@*, $topic->{filename} for $topic->{problems}->@*;
                    push @result_topics_for_section, $topic;
                }
                if (@result_topics_for_section) {
                    $section->{topics} = \@result_topics_for_section;
                    push @result_sections, $section;
                }
            }
            for my $sgj_obj ($collection->@*) {
                $sgj_obj->{related_positions} =
                  scalar($problems_with_collection_id{ $sgj_obj->{collection_id} }->@*);

                # include refs and tags so that subset filtering can work
                $sgj_obj->{$_} = $sgj_obj->{metadata}{$_} for qw(refs tags);
            }

            # delete entries from the topic index that don't have problems
            my @empty_topic_index_keys;
            while (my ($k, $v) = each %topic_index) {
                push @empty_topic_index_keys, $k if $v->{count} == 0;
            }
            delete @topic_index{@empty_topic_index_keys};
            return +{
                menu             => \@result_sections,
                by_collection_id => \%problems_with_collection_id,
                topic_index      => \%topic_index,
                full_collection  => $collection,
            };
        }
    );
}

sub get_basic_menu {

    # Use a sub, not a fixed array, to make clones, not shallow copies. If a
    # shallow copy is used multiple times, the subset code would mess up the
    # computed problem counts.
    my sub rank_subsets {
        return [
            { text => 'All' },
            {   text     => 'Opening',
                with_tag => 'opening',
            },
            {   text     => 'Attacking',
                with_tag => 'attacking',
            },
            {   text     => 'Defending',
                with_tag => 'defending',
            },
            {   text     => 'Living',
                with_tag => 'living',
            },
            {   text     => 'Killing',
                with_tag => 'killing',
            },
            {   text     => 'Endgame',
                with_tag => 'endgame',
            },
            {   text     => 'Joseki',
                with_ref => 'joseki',
            },
            {   text     => 'Capturing race',
                with_tag => 'capturing_race',
            },
        ];
    }
    my @menu = (
        {   text   => 'Techniques',
            topics => [
                {   with_tag => 'double_atari',
                    text     => 'Double atari',
                },
                {   with_tag => 'counteratari',
                    text     => 'Counter-atari',
                },
                {   with_tag => 'lining_up',
                    text     => 'Lining up',
                },
                {   with_tag => 'dent',
                    text     => 'Dent',
                },
                {   with_tag => 'wedge',
                    text     => 'Wedge',
                },
                {   with_tag => 'bend_wedge',
                    text     => 'Bend-wedge',
                },
                {   with_tag => 'clamp',
                    text     => 'Clamp',
                },
                {   with_tag => 'counterclamp',
                    text     => 'Counter-clamp',
                },
                {   with_tag => 'hane_and_cut',
                    text     => 'Hane and cut',
                },
                {   with_tag => 'hane_and_nakade',
                    text     => 'Hane and nakade',
                },
                {   with_tag => 'peep_and_cut',
                    text     => 'Peep and cut',
                },
                {   with_tag => 'push_and_cut',
                    text     => 'Push and cut',
                },
                {   with_tag => 'push_and_backtrack',
                    text     => 'Push and backtrack',
                },
                {   with_tag => 'jumping_over_wall',
                    text     => 'Jumping over the wall',
                },
                {   with_tag => 'attach_and_draw_back',
                    text     => 'Attach and draw back',
                },
                {   with_tag => 'attach_and_extend',
                    text     => 'Attach and extend',
                },
                {   with_tag => 'attach_and_hane',
                    text     => 'Attach and hane',
                },
                {   with_tag => 'attach_and_crosscut',
                    text     => 'Attach and crosscut',
                },
                {   with_tag => 'attach_and_block',
                    text     => 'Attach and block',
                },
                {   with_tag => 'attach_and_bulge',
                    text     => 'Attach and bulge',
                },
                {   with_tag => 'push_and_placement',
                    text     => 'Push and placement',
                },
                {   with_tag => 'clamp_against_attachment',
                    text     => 'Clamp against an attachment',
                },
                {   with_tag => 'elephant_eye',
                    text     => "Elephant's eye",
                },
                {   with_tag => 'diagonal_cover',
                    text     => 'Diagonal cover',
                },
                {   with_tag => 'knights_cover',
                    text     => "Knight's cover",
                },
                {   with_tag => 'large_knights_cover',
                    text     => "Large knight's cover",
                },
                {   with_tag => 'shoulder_hit',
                    text     => 'Shoulder hit',
                },
                {   with_tag => 'shoulder_cut',
                    text     => 'Shoulder cut',
                },
                {   with_tag => 'jump_attachment',
                    text     => 'Jump-attachment',
                },
                {   with_tag => 'nose_attachment',
                    text     => 'Nose attachment',
                },
                {   with_tag => 'table_attachment',
                    text     => 'Table attachment',
                },
                {   with_tag => 'anti_tower_peep_placement',
                    text     => 'Anti tower peep placement',
                },
                {   with_tag => 'belly_attachment',
                    text     => 'Belly attachment',
                },
                {   with_tag => 'armpit',
                    text     => 'Armpit',
                },
                {   with_tag => 'ankle_hook',
                    text     => 'Ankle hook',
                },
                {   with_tag => 'breaking_the_wing',
                    text     => 'Breaking the wing',
                },
                {   with_tag => 'cap',
                    text     => 'Cap',
                },
                {   with_tag => 'caterpillar_connection',
                    text     => 'Caterpillar connection',
                },
                {   with_tag => 'cave',
                    text     => 'Cave',
                },
                {   with_tag => 'cranes_nest',
                    text     => "Crane's nest",
                },
                {   with_tag => 'driving',
                    text     => 'Driving',
                },
                {   with_tag => 'dogleg',
                    text     => 'Dog leg',
                },
                {   with_tag => 'crawling_under_the_door',
                    text     => 'Crawling under the door',
                },
                {   with_tag => 'snapback',
                    text     => 'Snapback, all',
                },
                {   with_tag => 'double_snapback',
                    text     => 'Double snapback',
                    collate  => 'Snapback, double',
                },
                {   with_tag => 'double_hane_edge_squeeze',
                    text     => 'Double hane edge squeeze',
                },
                {   with_tag => 'eiffel_tower',
                    text     => 'Eiffel tower',
                },
                {   with_tag => 'eternal_life',
                    text     => 'Eternal life',
                },
                {   with_tag => 'eye_in_the_stomach',
                    text     => 'Eye in the stomach',
                },
                {   with_tag => 'flower_six',
                    text     => 'Flower six',
                },
                {   with_tag => 'grappling_hook',
                    text     => 'Grappling hook',
                },
                {   with_tag => 'hane_at_the_head',
                    text     => 'Hane at the head',
                },
                {   with_tag => 'ladder',
                    text     => 'Ladder',
                    collate  => 'Ladder, aaa',
                },
                {   with_tag => 'spiral_ladder',
                    text     => 'Spiral ladder',
                    collate  => 'Ladder, spiral',
                },
                {   with_tag => 'double_ladder',
                    text     => 'Double ladder',
                    collate  => 'Ladder, double',
                },
                {   with_tag => 'loose_ladder',
                    text     => 'Loose ladder',
                    collate  => 'Ladder, loose',
                },
                {   with_tag => 'squeezing',
                    text     => 'Squeezing',
                },
                {   with_tag => 'mouse_stealing_oil',
                    text     => 'Mouse stealing oil',
                },
                {   with_tag => 'monkey_jump',
                    text     => 'Monkey jump',
                },
                {   with_tag => 'net',
                    text     => 'Net',
                    collate  => 'Net, aaa',
                },
                {   with_tag => 'knights_net',
                    text     => "Knight's net",
                    collate  => 'Net, knights',
                },
                {   with_tag => 'first_line_descent',
                    text     => 'First-line descent',
                },
                {   with_tag => 'parallel_bars',
                    text     => 'Parallel bars',
                },
                {   with_tag => 'rooster_on_one_leg',
                    text     => 'Rooster on one leg',
                },
                {   with_tag => 'sacrifice_two',
                    text     => 'Sacrifice two stones',
                },
                {   with_tag => 'shimetsuke',
                    text     => 'Tightening',
                },
                {   with_tag => 'stick_connection',
                    text     => 'Stick connection',
                },
                {   with_tag => 'double_knights_connection',
                    text     => "Double knight's connection",
                },
                {   with_tag => 'symmetry',
                    text     => 'Symmetry',
                },
                {   with_tag => 'tanuki_belly',
                    text     => 'Tanuki drumming his belly',
                },
                {   with_tag => 'three_is_one',
                    text     => 'Three is one',
                },
                {   with_tag => 'tombstone',
                    text     => 'Tombstone',
                },
                {   with_tag => 'pushing_twice_then_keima',
                    text     => 'Pushing twice, then keima',
                },
                {   with_tag => 'cut_under_the_stones',
                    text     => 'Under the stones, then cut',
                },
                {   with_tag => 'placement_under_the_stones',
                    text     => 'Under the stones, then placement',
                },
                {   with_tag => 'windmill',
                    text     => 'Windmill',
                },
                {   with_tag => 'ko_lock',
                    text     => 'Ko lock',
                },
                {   with_tag => 'connect_and_die',
                    text     => 'Connect and die',
                },
                {   with_tag => 'elbow_lock',
                    text     => 'Elbow lock',
                },
                {   with_tag => 'carpenters_connection',
                    text     => "Carpenter's square connection",
                },
                {   with_tag => 'guzumi',
                    text     => 'Good empty triangle',
                },
                {   with_tag => 'cork_in_the_bottle',
                    text     => 'Cork in the bottle',
                },
                {   with_tag => 'angle_play',
                    text     => 'Angle play',
                },
                {   with_tag => 'crosscut',
                    text     => 'Crosscut',
                },
                {   with_tag => 'peep',
                    text     => 'Peep',
                    collate  => 'Peep, aaa',
                },
                {   with_tag => 'resisting_peep',
                    text     => 'Resisting a peep',
                    collate  => 'Peep, resisting',
                },
                {   with_tag => 'preventing_bamboo',
                    text     => 'Preventing the bamboo',
                },
                {   with_tag => 'cut_to_defend_cut',
                    text     => 'Cut to defend against a cut',
                },
                {   with_tag => 'daidaigeima',
                    text     => "Extra-large knight's move",
                },
                {   with_tag => 'pushing_from_behind',
                    text     => 'Pushing from behind',
                },
                {   with_tag => 'second_line_diagonal',
                    text     => 'Diagonal move on the second line',
                },
                {   with_tag => 'two_recapture_one',
                    text     => 'Capturing two stones, recapturing one',
                },
                {   with_tag => 'capturing_two_for_two_eyes',
                    text     => 'Capturing two stones, getting two eyes',
                },
                {   with_tag => 'wedge_separate',
                    text     => 'Wedge to separate',
                },
                {   with_tag => 'invading_3_extension',
                    text     => 'Invading a three-space extension',
                },
                {   with_tag => 'trumpet_connection',
                    text     => 'Trumpet connection',
                },
                {   with_tag => 'unstable_connection',
                    text     => 'Unstable connections',
                },
                {   with_tag => 'cat_face',
                    text     => "Cat's face",
                    collate  => 'Face, cat',
                },
                {   with_tag => 'dog_face',
                    text     => "Dog's face",
                    collate  => 'Face, dog',
                },
                {   with_tag => 'breaking_dog_face',
                    text     => "Breaking the dog's face",
                    collate  => 'Face, dog, break',
                },
                {   with_tag => 'horse_face',
                    text     => "Horse's face",
                    collate  => 'Face, horse',
                },
                {   with_tag => 'giraffe_face',
                    text     => "Giraffe's face",
                    collate  => 'Face, giraffe',
                },
                {   with_tag => 'bumping',
                    text     => 'Bumping',
                },
                {   with_tag => 'flying_double_clamp',
                    text     => 'Flying double clamp',
                },
                {   with_tag => 'throwing_in',
                    text     => 'Throwing in',
                },
                {   with_tag => 'crossing_the_lair',
                    text     => 'Crossing the Lair',
                },
                {   with_tag => 'pinch',
                    text     => 'Pinch',
                },
                {   with_tag => 'braid',
                    text     => 'Braid',
                },
                {   with_tag => 'first_line_empty_triangle',
                    text     => 'Empty triangle on the first line',
                },
                {   with_tag => 'across_attach',
                    text     => 'Across attach',
                },
                {   with_tag => 'rhombus_attach',
                    text     => 'Rhombus attach',
                },
                {   with_tag => 'diagonal_attachment',
                    text     => 'Diagonal attachment',
                },
                {   with_tag => 'tigers_mouth',
                    text     => "Tiger's mouth",
                },
                {   with_tag => 'nobikiri',
                    text     => 'Stretching in',
                },
                {   with_tag => 'bad_sente',
                    text     => 'Bad sente',
                },
                {   with_tag => 'making_a_false_eye',
                    text     => 'Making a false eye',
                },
            ]
        },
        {   text   => 'Opening',
            topics => [
                {   with_tag => 'making_a_position',
                    text     => 'Making a position',
                },
                {   with_tag => 'extending',
                    text     => 'Extending',
                },
                {   with_tag => 'drawing_near',
                    text     => 'Drawing near',
                },
                {   with_tag => 'checking_extension',
                    text     => 'Checking extension',
                },
                {   with_tag => 'enlarging',
                    text     => 'Enlarging',
                },
                {   with_tag => 'making_a_triangular_framework',
                    text     => 'Making a triangular framework',
                    collate  => 'Framework, 3, making',
                },
                {   with_tag => 'preventing_a_triangular_framework',
                    text     => 'Preventing a triangular framework',
                    collate  => 'Framework, 3, preventing',
                },
                {   with_tag => 'making_a_rectangular_framework',
                    text     => 'Making a rectangular framework',
                    collate  => 'Framework, 4, making',
                },
                {   with_tag => 'enlarging_while_limiting',
                    text     => 'Enlarging while limiting',
                },
                {   with_tag => 'reducing_from_above',
                    text     => 'Reducing from above',
                },
                {   with_tag => 'surrounding',
                    text     => 'Surrounding',
                },
                {   with_ref => 'fuseki/low-chinese',
                    text     => 'Low chinese fuseki',
                    collate  => 'Fuseki, chinese, low',
                },
                {   with_ref => 'fuseki/high-chinese',
                    text     => 'High chinese fuseki',
                    collate  => 'Fuseki, chinese, high',
                },
                {   with_ref => 'fuseki/mini-chinese',
                    text     => 'Mini chinese fuseki',
                    collate  => 'Fuseki, chinese, mini',
                },
                {   with_ref => 'fuseki/micro-chinese',
                    text     => 'Micro chinese fuseki',
                    collate  => 'Fuseki, chinese, micro',
                },
                {   with_tag => 'kobayashi_fuseki',
                    text     => '@fuseki/kobayashi',
                    collate  => 'Fuseki, Kobayashi',
                },
                {   with_ref => 'fuseki/facing-34',
                    text     => 'Facing 3-4 points',
                    collate  => 'Fuseki, 3-4, facing',
                },
                {   with_ref => 'fuseki/opposing-34',
                    text     => 'Opposing 3-4 points',
                    collate  => 'Fuseki, 3-4, opposing',
                },
                {   with_ref => 'fuseki/nirensei',
                    text     => 'Nirensei',
                    collate  => 'Fuseki, star points, 2',
                },
                {   with_ref => 'fuseki/sanrensei',
                    text     => 'Sanrensei',
                    collate  => 'Fuseki, star points, 3',
                }
            ]
        },
        {   topics => [
                {   with_tag => 'separating',
                    text     => 'Separating',
                },
                {   with_tag => 'pressing_down',
                    text     => 'Pressing down',
                },
                {   with_tag => 'sealing_in',
                    text     => 'Sealing in',
                },
                {   with_tag => 'spoiling_shape',
                    text     => 'Spoiling shape, all',
                    collate  => 'Spoiling shape, aaa',
                },
                {   with_tag    => 'forcing_into_empty_triangle',
                    without_tag => 'forcing_into_farmers_hat',
                    text        => 'Empty triangle',
                    collate     => 'Spoiling shape, empty triangle',
                    thumbnail   => 'empty-triangle.png',
                },
                {   with_tag => 'forcing_into_farmers_hat',
                    text     => "Farmer's hat",
                    collate  => "Spoiling shape, farmer's hat",
                },
                {   with_tag => 'forcing_into_dumpling',
                    text     => 'Dumpling',
                    collate  => 'Spoiling shape, dumpling',
                },
                {   with_tag => 'probing',
                    text     => 'Probing',
                },
                {   with_tag => 'making_heavy',
                    text     => 'Making heavy',
                },
                {   with_tag => 'overconcentrating',
                    text     => 'Overconcentrating',
                },
                {   with_tag => 'creating_weaknesses',
                    text     => 'Creating weaknesses',
                    collate  => 'Creating weaknesses, aaa',
                },
                {   with_tag => 'creating_cuts',
                    text     => 'Creating cuts',
                    collate  => 'Creating weaknesses, cuts',
                },
                {   with_tag => 'making_double_threats',
                    text     => 'Making double threats',
                },
                {   with_tag => 'taking_away_base',
                    text     => 'Taking away the base',
                },
                {   with_tag => 'capturing',
                    text     => 'Capturing',
                },
                {   with_tag => 'making_territory',
                    text     => 'Making territory',
                },
                {   with_tag => 'intimidating_with_ko',
                    text     => 'Intimidating with ko',
                },
                {   with_tag => 'making_fist',
                    text     => 'Making a fist',
                },
                {   with_tag => 'invading',
                    text     => 'Invading',
                },
                {   with_tag => 'kikashi',
                    text     => 'Kikashi',
                },
                {   with_tag => 'bullying',
                    text     => 'Bullying',
                },
                {   with_tag => 'capping',
                    text     => 'Capping',
                },
                {   with_tag => 'leaning_attack',
                    text     => 'Leaning attack',
                },
                {   with_tag => 'splitting_attack',
                    text     => 'Splitting attack',
                },
            ],
            text => 'Attacking',
        },
        {   topics => [
                {   with_tag => 'connecting',
                    text     => 'Connecting',
                },
                {   with_tag => 'capturing_key_stones',
                    text     => 'Capturing key stones',
                },
                {   with_tag => 'developing',
                    text     => 'Developing',
                },
                {   with_tag => 'escaping',
                    text     => 'Escaping',
                },
                {   with_tag => 'making_shape',
                    text     => 'Making shape',
                },
                {   with_tag => 'taking_sente',
                    text     => 'Taking sente',
                },
                {   with_tag => 'sabaki',
                    text     => 'Handling weak stones',
                },
                {   with_tag => 'striking_back',
                    text     => 'Striking back',
                },
                {   with_tag => 'defending_against_multiple_threats',
                    text     => 'Defending against multiple threats',
                },
                {   with_tag => 'solidifying_base',
                    text     => 'Solidifying the base',
                },
                {   with_tag => 'defending_base',
                    text     => 'Defending the base',
                },
                {   with_tag => 'linking_up',
                    text     => 'Linking up',
                },
                {   with_tag => 'resisting_with_ko',
                    text     => 'Resisting with ko',
                },
                {   with_tag => 'forcing_before_defending',
                    text     => 'Forcing before defending',
                },
                {   with_tag => 'indirect_defense',
                    text     => 'Indirect defense',
                },
                {   with_tag => 'refuting_overplay',
                    text     => 'Refuting an overplay',
                },
                {   with_tag => 'trick_play',
                    text     => 'Trick play',
                },
                {   with_tag => 'deny_kikashi',
                    text     => 'Denying kikashi',
                }
            ],
            text => 'Defending',
        },
        {   topics => [
                {   with_tag => 'sacrificing_junk_stones',
                    text     => 'Sacrificing junk stones',
                },
                {   with_tag => 'chasing_junk_stones',
                    text     => 'Chasing junk stones',
                },
                {   with_tag => 'walking_ahead',
                    text     => 'Walking ahead',
                },
                {   with_tag => 'pushing_from_weak_area',
                    text     => 'Pushing from weakness',
                },
                {   with_tag => 'joseki_choice',
                    text     => 'Choice of joseki',
                },
                {   with_tag => 'direction_of_attack',
                    text     => 'Direction of attack',
                },
                {   with_tag => 'value_of_sides',
                    text     => 'Value of sides',
                },
                {   with_tag => 'playing_away_from_thickness',
                    text     => 'Playing away from thickness',
                },
                {   with_tag => 'avoiding_being_enclosed',
                    text     => 'Avoiding being enclosed',
                },
                {   with_tag => 'leaving_aji',
                    text     => 'Leaving aji',
                },
                {   with_tag => 'good_ugly_keima_cut',
                    text     => 'Good ugly keima cut',
                },
                {   with_tag => 'tenuki',
                    text     => 'Tenuki',
                },
                {   with_tag => 'running_battle',
                    text     => 'Running battle',
                },
                {   with_tag => 'tennouzan',
                    text     => 'Commanding the high point',
                },
                {   with_tag => 'crossfight',
                    text     => 'Four cut groups',
                }
            ],
            text => 'Strategy',
        },
        {   topics => [
                {   filter    => '#solidifying_base and #taking_away_base',
                    text      => 'Base of both sides',
                    thumbnail => 'base-of-both-sides.png',
                },
                {   with_tag => 'handling_invasion',
                    text     => 'Handling an invasion',
                },
                {   with_tag => 'speculative_invasion',
                    text     => 'Speculative invasion',
                }
            ],
            text => 'Multiple objectives',
        },
        {   topics => [
                {   with_tag => 'breaking_in',
                    text     => 'Breaking in',
                },
                {   with_tag => 'encroaching',
                    text     => 'Encroaching on territory',
                    collate  => 'Encroaching, doing',
                },
                {   with_tag => 'stopping_encroachments',
                    text     => 'Stopping encroachments',
                    collate  => 'Encroaching, stopping',
                },
                {   with_tag => 'large_yose',
                    text     => 'Large yose',
                },
                {   with_tag => 'threatening_to_kill',
                    text     => 'Threatening to kill',
                },
                {   with_tag => 'forcing_removal',
                    text     => 'Forcing removal',
                },
                {   with_tag => 'double_endgame_attacks',
                    text     => 'Double endgame attacks',
                },
                {   with_tag => 'double_endgame_defenses',
                    text     => 'Double endgame defenses',
                },
                {   with_tag => 'closing_in_sente',
                    text     => 'Closing boundaries in sente',
                }
            ],
            text => 'Endgame',
        },
        {   text   => 'Living',
            topics => [
                {   with_tag => 'living',
                    text     => 'All',
                    rel_text => 'Living, all',
                    collate  => 'Living, aaa',
                },
                {   with_tag => 'securing_eye_shape',
                    text     => 'Securing eye shape',
                    rel_text => 'Living by securing eye shape',
                    collate  => 'Living, securing eye shape',
                },
                {   with_tag => 'enlarging_eye_space',
                    text     => 'Enlarging eye space',
                    rel_text => 'Living by enlarging eye space',
                    collate  => 'Living, enlarging eye space',
                },
                {   with_tag => 'living_with_false_eyes',
                    text     => 'Living with false eyes',
                    collate  => 'Living, false eyes',
                },
                {   with_tag => 'living_with_seki',
                    text     => 'Living with seki',
                    collate  => 'Living, seki',
                },
                {   with_tag => 'squashing',
                    text     => 'Squashing',
                    rel_text => 'Living by squashing',
                    collate  => 'Living, squashing',
                },
                {   text     => 'Living with Ko',
                    with_tag => 'living_with_ko',
                    collate  => 'Living, ko, 1',
                },
                {   text     => 'Living with double ko',
                    with_tag => 'living_with_double_ko',
                    collate  => 'Living, ko, 2',
                },

                # Making one eye
                {   with_ref => 'tsumego/making-one-eye/other',
                    text     => 'Making one eye, other',
                    collate  => 'Making one eye, 2',
                },
                {   with_ref => 'tsumego/making-one-eye/second-line-shape',
                    text     => 'Making one eye, second-line shapes',
                    collate  => 'Making one eye, 1',
                },
            ]
        },
        {   text   => 'Killing',
            topics => [
                {   with_tag => 'killing',
                    text     => 'All',
                    rel_text => 'Killing, all',
                    collate  => 'Killing, aaa',
                },
                {   with_tag => 'nakade',
                    text     => 'Nakade',
                    rel_text => 'Killing with nakade',
                    collate  => 'Killing, nakade',
                },
                {   with_tag => 'bent_four_in_the_corner',
                    text     => 'Bent four in the corner',
                    collate  => 'Killing, bent four in the corner',
                },
                {   with_tag => 'killing_with_ko',
                    text     => 'Killing with ko',
                    collate  => 'Killing, ko, 1',
                },
                {   with_tag => 'killing_with_double_ko',
                    text     => 'Killing with double ko',
                    collate  => 'Killing, ko, 2',
                },
                {   with_tag => 'ten_thousand_year_ko',
                    text     => '10,000 year ko',
                    collate  => 'Killing, ko, 3',
                },
            ]
        },
        {   text   => 'Real-game life-and-death',
            topics => [

                # Real-game corners
                {   with_ref => 'tsumego/real/corner',
                    text     => 'Real-game corners, all',
                    collate  => 'Real-game corners, aaa',
                },
                {   with_ref => 'tsumego/real/corner/small-pig-snout',
                    text     => 'Small pig snout',
                    collate  => 'Real-game corners, pig snout, 1',
                },
                {   with_ref => 'tsumego/real/corner/big-pig-snout',
                    text     => 'Big pig snout',
                    collate  => 'Real-game corners, pig snout, 2',
                },
                {   with_ref => 'tsumego/real/corner/rectangular-six',
                    text     => 'Rectangular six in the corner',
                    collate  => 'Real-game corners, rectangular six',
                },
                {   with_ref => 'tsumego/real/corner/l-group',
                    text     => 'L-group',
                    collate  => 'Real-game corners, l group, 1',
                },
                {   with_ref => 'tsumego/real/corner/long-l-group',
                    text     => 'Long L-group',
                    collate  => 'Real-game corners, l group, 2',
                },
                {   with_ref => 'tsumego/real/corner/carpenters-square',
                    text     => "Carpenter's square",
                    collate  => "Real-game corners, carpenter's square",
                },

                # Real-game sides
                {   with_ref => 'tsumego/real/side',
                    text     => 'Real-game sides, All',
                    collate  => 'Real-game sides, aaa',
                },
                {   with_ref => 'tsumego/real/side/notcher',
                    text     => 'Notchers, all',
                    collate  => 'Real-game sides, notchers, all',
                },
                {   with_ref => 'tsumego/real/side/notcher',
                    with_tag => 'status',
                    text     => 'Notchers, status',
                    collate  => 'Real-game sides, notchers, status',
                },
                {   with_ref => 'notcher/length/1',
                    text     => 'Notchers, one-space',
                    collate  => 'Real-game sides, notchers, 1-space',
                },
                {   with_ref => 'notcher/length/2',
                    text     => 'Notchers, two-space',
                    collate  => 'Real-game sides, notchers, 2-space',
                },
                {   with_ref => 'notcher/length/3',
                    text     => 'Notchers, three-space',
                    collate  => 'Real-game sides, notchers, 3-space',
                },
                {   with_ref => 'tsumego/real/side/door',
                    text     => 'Door group',
                    collate  => 'Real-game sides, door group',
                },
                {   with_ref => 'tsumego/real/side/comb',
                    text     => 'Comb formation',
                    collate  => 'Real-game sides, comb',
                },
            ]
        },
        {   text   => 'Capturing race',
            topics => [
                {   with_tag => 'capturing_race',
                    text     => 'All',
                    rel_text => 'Capturing race, all',
                },
                {   with_tag => 'extending_liberties',
                    text     => 'Extending liberties',
                    rel_text => 'Capturing race, extending liberties',
                },
                {   with_tag => 'reducing_liberties',
                    text     => 'Reducing liberties',
                    rel_text => 'Capturing race, reducing liberties',
                },
                {   with_tag => 'capturing_race_ko',
                    text     => 'Ko',
                    rel_text => 'Capturing race, ko',
                },
                {   with_tag => 'capturing_race_seki',
                    text     => 'Seki',
                    rel_text => 'Capturing race, seki',
                },
                {   with_tag => 'one_eye_no_eye',
                    text     => 'Eye vs. no eye',
                    rel_text => 'Capturing race, eye vs. no eye',
                },
                {   with_tag => 'destroying_one_eye',
                    text     => 'Destroying one eye',
                    rel_text => 'Capturing race, destroying one eye',
                }
            ]
        },
        {   topics => [
                {   with_ref => 'joseki/33/44',
                    text     => '3-3',
                    rel_text => '3-3, 4-4 cover',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/33/approach',
                    text     => '3-3',
                    rel_text => '3-3, side approach',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/diag/3lxt',
                    text     => '3-4',
                    rel_text =>
                      "3-4, knight's approach, Shusaku's diagonal, three-space low extension",
                    collate => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/1kxt/3lxt',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, knight's defense, extension",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/1kxt/33',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, knight's defense, 3-3",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/1hp',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, one-space high pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/1lp',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, one-space low pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/2hp',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, two-space high pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1lap/tenuki/3lap',
                    text     => '3-4',
                    rel_text => "3-4, knight's approach, tenuki, three-space low approach",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1hp',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space high pincer',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/attach-inside-to-corner/wedge',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space low pincer, 3-3, wedge',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/attach-inside-to-corner/hane',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space low pincer, 3-3, hane',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/attach-inside-to-corner/2lxt',
                    text     => '3-4',
                    rel_text =>
                      '3-4, one-space approach, one-space low pincer, 3-3, two-space extension',
                    collate => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/diag-to-pincer',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space low pincer, diagonal',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/jump-descent',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space low pincer, jump descent',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lp/knight-to-corner',
                    text     => '3-4',
                    rel_text => "3-4, one-space approach, one-space low pincer, knight's cover",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/1lxt',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space extension',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/2hp',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, one-space high pincer',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/attach-inside/hane',
                    text     => '3-4',
                    rel_text => '3-4, one-space approach, inside attachment, hane',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/attach-inside/avalanche/small',
                    text     => '3-4',
                    rel_text => '3-4, small avalanche',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/1hap/attach-inside/avalanche/large',
                    text     => '3-4',
                    rel_text => '3-4, large avalanche',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/2lap/1hs',
                    text     => '3-4',
                    rel_text => "3-4, large knight's approach, high enclosure",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/2lap/1lp',
                    text     => '3-4',
                    rel_text => "3-4, large knight's approach, one-space low pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/34/2hap/tenuki/attach-inside-to-corner',
                    text     => '3-4',
                    rel_text => '3-4, two-space approach, tenuki, 3-3',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/1lp',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, one-space low pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/1hp',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, one-space high pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/33',
                    text     => '4-4',
                    rel_text => '4-4, 3-3 invasion',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/1lxt',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, knight's extension",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/1hxt',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, one-space extension",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/2hp',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, two-space high pincer",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/tenuki/1lap',
                    text     => '4-4',
                    rel_text => "4-4, double knight's approach",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/1lp/1lap',
                    text     => '4-4',
                    rel_text =>
                      "4-4, knight's approach, one-space low pincer, double knight's approach",
                    collate => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/2hp/1lap',
                    text     => '4-4',
                    rel_text =>
                      "4-4, knight's approach, two-space high pincer, double knight's approach",
                    collate => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/attach-extend',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, attach-extend",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/44/1lap/diag',
                    text     => '4-4',
                    rel_text => "4-4, knight's approach, Takemiya diagonal",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/54/34/attach-inside-to-corner',
                    text     => '5-4',
                    rel_text => '5-4, 3-4, 3-3 attachment',
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/53/34/knights-cover',
                    text     => '5-3',
                    rel_text => "5-3, 3-4, knight's cover",
                    collate  => $FILTER,
                },
                {   with_ref => 'joseki/53/34/large-knights-cover',
                    text     => '5-3',
                    rel_text => "5-3, 3-4, large knight's cover",
                    collate  => $FILTER,
                }
            ],
            text => 'Joseki',
        },
        {   topics => [
                {   with_ref => 'enclosure/34/1hs',
                    text     => '3-4',
                    rel_text => '3-4, one-space enclosure',
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/34/2ls',
                    text     => '3-4',
                    rel_text => "3-4, large knight's enclosure",
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/44/1ls',
                    text     => '4-4',
                    rel_text => "4-4, knight's enclosure",
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/44/1ls/6lxt',
                    text     => '4-4',
                    rel_text => "4-4, knight's enclosure plus six-space low extension",
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/44/2ls',
                    text     => '4-4',
                    rel_text => "4-4, large knight's enclosure",
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/44/5hxt',
                    text     => '4-4',
                    rel_text => '4-4, five-space high wing',
                    collate  => $FILTER,
                },
                {   with_ref => 'enclosure/44/5lxt',
                    text     => '4-4',
                    rel_text => '4-4, five-space low wing',
                    collate  => $FILTER,
                }
            ],
            text => 'Enclosures',
        },
        {   topics => [
                {   with_tag => 'question',
                    text     => 'Question-and-answer',
                },
                {   with_tag => 'show_choices',
                    text     => 'Show next move choices',
                },
                {   with_tag => 'rate_choices',
                    text     => 'Rate multiple choices',
                },
                {   with_tag => 'multiple_choice',
                    text     => 'Multiple choice',
                },
                {   with_ref => 'joseki',
                    with_tag => 'copy',
                    text     => 'Copy joseki',
                },
                {   with_tag => 'status',
                    text     => 'Life-and-death status',
                },
                {   with_tag => 'sujiba',
                    text     => 'Sujiba theory',
                },
                {   with_tag => 'counting_score',
                    text     => 'Count the score',
                },
                {   with_tag => 'calculating_move_value',
                    text     => "Calculate a move's value",
                },
                {   with_tag => 'debug',
                    text     => 'Debug',
                }
            ],
            text => 'Tasks',
        },
        {   topics => [
                {   with_tag => 'rank_intro',
                    text     => 'Introductory',
                    rel_text => 'Introductory Problems',
                    collate  => '0',
                    subsets  => rank_subsets(),
                },
                {   with_tag => 'rank_elementary',
                    text     => 'Elementary',
                    rel_text => 'Elementary Problems',
                    collate  => '1',
                    subsets  => rank_subsets(),
                },
                {   with_tag => 'rank_intermediate',
                    text     => 'Intermediate',
                    rel_text => 'Intermediate Problems',
                    collate  => '2',
                    subsets  => rank_subsets(),
                },
                {   with_tag => 'rank_advanced',
                    text     => 'Advanced',
                    rel_text => 'Advanced Problems',
                    collate  => '3',
                    subsets  => rank_subsets(),
                },
                {   with_tag => 'rank_low_dan',
                    text     => 'Low-dan',
                    rel_text => 'Low-dan Problems',
                    collate  => '4',
                    subsets  => rank_subsets(),
                },
                {   with_tag => 'rank_high_dan',
                    text     => 'High-dan',
                    rel_text => 'High-dan Problems',
                    collate  => '5',
                    subsets  => rank_subsets(),
                },
            ],
            text => 'By Level',
        },
        {   text   => 'Games',
            topics => [
                {   with_tag => 'progame',
                    text     => 'Professional games',
                },
                {   with_tag => 'game',
                    text     => 'Any real game',
                }
            ]
        },
        {   text   => 'Yunguseng Dojang',
            topics => [
                {   with_ref => 'yunguseng-dojang/lectures/09/1',
                    text =>
                      "S09 lecture 1: Across attach; Break the dog's face; Indirect defense (Local Technique)",
                    rel_text => 'S09 lecture 1',
                },
                {   with_ref => 'yunguseng-dojang/lectures/26/1',
                    text     => 'S26 lecture 1: Pinch (Local Technique)',
                },
                {   with_ref => 'yunguseng-dojang/lectures/26/3',
                    text     => 'S26 lecture 3: Kick and jump (Pattern)',
                },
            ]
        },
        {   text => 'Old Classic Books',

            # Old classics don't have @p/ refs and so are public.
            topics => [
                {   text     => 'Gokyo Shumyo',
                    with_ref => 'gokyo-shumyo',
                    subsets  => [
                        { text => 'All' },
                        {   text     => 'Living',
                            with_ref => 'gokyo-shumyo/live',
                        },
                        {   text     => 'Killing',
                            with_ref => 'gokyo-shumyo/kill',
                        },
                        {   text     => 'Ko',
                            with_ref => 'gokyo-shumyo/ko',
                        },
                        {   text     => 'Capturing race',
                            with_ref => 'gokyo-shumyo/semeai',
                        },
                        {   text     => 'Connect and die',
                            with_ref => 'gokyo-shumyo/oiotoshi',
                        },
                        {   text     => 'Connecting',
                            with_ref => 'gokyo-shumyo/watari',
                        },
                        {   text     => 'Wedge and others',
                            with_ref => 'gokyo-shumyo/warikomi-nado',
                        },
                        {   text     => "ツヅキ",
                            with_ref => 'gokyo-shumyo/tsuduki',
                        },
                        {   text     => 'Cut',
                            with_ref => 'gokyo-shumyo/kiri',
                        },
                        {   text     => 'Ladder',
                            with_ref => 'gokyo-shumyo/shichou',
                        },
                    ],
                },
                {   with_ref => 'kanzufu',
                    text     => 'Kanzufu',
                    subsets  => [
                        { text => 'All' },
                        {   text     => 'Attack and Defense',
                            with_ref => 'kanzufu/attack-defense',
                        },
                        {   text     => 'Technique',
                            with_ref => 'kanzufu/technique',
                        },
                        {   text     => 'Tesuji',
                            with_ref => 'kanzufu/tesuji',
                        },
                        {   text     => 'Connection',
                            with_ref => 'kanzufu/connection',
                        },
                        {   text     => 'Life-and-death',
                            with_ref => 'kanzufu/life-and-death',
                        },
                        {   text     => 'Endgame',
                            with_ref => 'kanzufu/endgame',
                        },
                    ],
                },
                {   with_ref => 'gengen-gokyo',
                    text     => 'Gengen Gokyo',
                },
                {   with_ref => 'shikatsu-myoki',
                    text     => 'Shikatsu Myoki',
                },
                {   with_ref => 'igo-hatsuyoron',
                    text     => 'Igo Hatsuyoron',
                },
                {   with_ref => 'gokyo-seimyo',
                    text     => 'Gokyo Seimyo',
                },
                {   with_ref => 'genran',
                    text     => 'Genran',
                }
            ]
        },
    );
    return @menu;
}

# support some computed properties to avoid duplication and clutter
sub handle_computed_properties_for_section ($section) {
    for my $topic ($section->{topics}->@*) {
        $topic->{id} = get_topic_id($topic);
        if (defined($topic->{collate}) && $topic->{collate} eq $FILTER) {
            $topic->{collate} = $topic->{id};
        }
        if (($topic->{thumbnail} // $FILTER) eq $FILTER) {

            # e.g., '@joseki/33/approach' becomes 'joseki-33-approach.png'
            $topic->{thumbnail} = "$topic->{id}.png";
        }
        if (defined $topic->{subsets}) {
            for my $subset ($topic->{subsets}->@*) {
                my $s = sprintf '%s %s %s %s',
                  map { $_ // 'undef' }
                  $subset->@{qw(with_ref without_ref with_tag without_tag)};
                $subset->{id} = utf8_sha1_hex($s);
            }
        }
    }
}

sub read_menu ($path) {
    my $p = path($path);
    $p->exists  or die "menu $path does not exist\n";
    $p->is_file or die "menu $path is not a file\n";
    my ($json, $data);
    eval { $json = $p->slurp_utf8 };
    $@ && die "can't read menu $path: $@\n";
    eval { $data = json_decode($json) };
    $@ && die "can't decode JSON from menu $path\n";
    return $data;
}

# Generate an id that can be used for the collection filename, thumbnail
# filename and topic collation. Construct something that looks like a filter
# corresponding to the with/without spec.
sub get_topic_id ($topic) {
    my $id =
      join ' and ' => (defined $topic->{with_tag} ? ($topic->{with_tag}) : ()),
      (defined $topic->{without_tag} ? ('not', $topic->{without_tag}) : ()),
      (defined $topic->{with_ref}    ? ($topic->{with_ref})           : ()),
      (defined $topic->{without_ref} ? ('not', $topic->{without_ref}) : ()),
      (defined $topic->{filter}      ? ($topic->{filter})             : ());
    $id =~ s/[\#\@]//g;
    $id =~ s![ _/]!-!g;
    return $id;
}
1;
